import assert from 'assert';
import { CancellationToken } from '../../../../../base/common/cancellation.js';
import { URI } from '../../../../../base/common/uri.js';
import { FileOperationError, FileOperationResult } from '../../../../../platform/files/common/files.js';
import { AgentSkillsService } from '../../browser/agentSkillsService.js';
import { projectAgentConfig } from '../../common/agentInstructions.js';

const enc = new TextEncoder();
const uri = (path: string) => URI.parse(`file://${path}`);
const skill = (name: string, body = 'body') => `---\nname: ${name}\ndescription: ${name} description\n---\n${body}`;

type Node = { dir?: true; data?: Uint8Array; link?: true; unreadable?: true };
class Files {
	readonly nodes = new Map<string, Node>();
	private key(path: string) { return /^[a-z][a-z0-9+.-]*:/i.test(path) ? path : `file://${path}`; }
	put(path: string, value: string | Uint8Array, extra: Node = {}) { this.nodes.set(this.key(path), { data: typeof value === 'string' ? enc.encode(value) : value, ...extra }); }
	dir(path: string, extra: Node = {}) { this.nodes.set(this.key(path), { dir: true, ...extra }); }
	async resolve(resource: URI): Promise<any> {
		const key = resource.toString(); const node = this.nodes.get(key);
		if (!node || node.unreadable) throw new FileOperationError('missing', FileOperationResult.FILE_NOT_FOUND);
		const prefix = `${key}/`; const children = [...this.nodes.entries()].filter(([child]) => child.startsWith(prefix) && !child.slice(prefix.length).includes('/')).map(([child, value]) => ({ resource: URI.parse(child), isDirectory: !!value.dir, isFile: !value.dir, isSymbolicLink: !!value.link }));
		return { resource, isDirectory: !!node.dir, isFile: !node.dir, isSymbolicLink: !!node.link, children };
	}
	async readFile(resource: URI): Promise<any> { const node = this.nodes.get(resource.toString()); if (!node || node.dir || node.unreadable) throw new FileOperationError('missing', FileOperationResult.FILE_NOT_FOUND); return { value: { buffer: node.data! } }; }
}
const fixture = (initiallyTrusted = true) => {
	let trusted = initiallyTrusted; const files = new Files(); const extensions: any[] = []; const extensionService = { extensions, whenInstalledExtensionsRegistered: async () => { } };
	const service = new AgentSkillsService(files as never, { userHome: async () => uri('/home') } as never, { isWorkspaceTrusted: () => trusted } as never, extensionService as never);
	return { files, service, extensions, extensionService, setTrusted: (value: boolean) => trusted = value };
};
const roots = (files: Files) => { for (const path of ['/repo', '/repo/.agents', '/repo/.agents/skills', '/repo/nested', '/repo/nested/.agents', '/repo/nested/.agents/skills', '/home', '/home/.agents', '/home/.agents/skills']) files.dir(path); };

suite('Agent Skills browser service', () => {
	test('admits trusted repository roots through nested CWD only and excludes them when untrusted', async () => {
		const { files, service, extensions, extensionService, setTrusted } = fixture(); roots(files); files.dir('/repo/.agents/skills/root'); files.put('/repo/.agents/skills/root/SKILL.md', skill('root')); files.dir('/repo/nested/.agents/skills/nested'); files.put('/repo/nested/.agents/skills/nested/SKILL.md', skill('nested')); files.dir('/sibling/.agents/skills/nope'); files.put('/sibling/.agents/skills/nope/SKILL.md', skill('nope'));
		assert.deepStrictEqual((await service.getCatalog(uri('/repo'), uri('/repo/nested'))).skills.map(s => s.identity), ['root', 'nested']);
		files.dir('/home/.agents/skills/user'); files.put('/home/.agents/skills/user/SKILL.md', skill('user')); for (const path of ['/plugin', '/plugin/.codex-plugin', '/plugin/skills', '/plugin/skills/plug']) files.dir(path); files.put('/plugin/.codex-plugin/plugin.json', JSON.stringify({ name: 'plugin', skills: './skills/' })); files.put('/plugin/skills/plug/SKILL.md', skill('plug')); extensions.push({ extensionLocation: uri('/plugin') }); const staleProjectConfig = projectAgentConfig(undefined, { skillConfigRules: [{ selector: { kind: 'name', value: 'user' }, enabled: false, source: 'project' }], skillConfigDiagnostics: [{ source: 'project', index: 0, reason: 'unknown_key', code: 'skill_config_invalid' }], skillsConfigPresent: true }, [], 'file:///repo', 'file:///repo'); let release!: () => void; let entered!: () => void; const waiting = new Promise<void>(resolve => entered = resolve); const registrationReady = new Promise<void>(resolve => release = resolve); extensionService.whenInstalledExtensionsRegistered = () => { entered(); return registrationReady; }; const pending = service.getCatalog(uri('/repo'), uri('/repo/nested'), staleProjectConfig); await waiting; setTrusted(false); release(); const downgraded = await pending; assert.strictEqual(downgraded.skills.some(s => s.provenance.source === 'repository'), false); assert.strictEqual(downgraded.diagnostics.some(d => (d.detail ?? '').includes('file:///repo') || d.detail === 'project'), false); assert.deepStrictEqual(downgraded.skills.map(s => [s.identity, s.provenance.source]), [['user', 'user'], ['plugin:plug', 'plugin']]);
		const untrusted = fixture(false); roots(untrusted.files); untrusted.files.dir('/repo/.agents/skills/root'); untrusted.files.put('/repo/.agents/skills/root/SKILL.md', skill('root')); assert.strictEqual((await untrusted.service.getCatalog(uri('/repo'), uri('/repo'))).skills.length, 0);
	});
	test('admits user-root Skills independently of workspace ownership', async () => { const { files, service } = fixture(false); roots(files); files.dir('/home/.agents/skills/user'); files.put('/home/.agents/skills/user/SKILL.md', skill('user')); assert.deepStrictEqual((await service.getCatalog(undefined, undefined)).skills.map(s => s.identity), ['user']); });
	test('waits for live enabled extensions and uses canonical manifests across local and remote roots', async () => {
		const { files, extensionService, extensions } = fixture(); let release!: () => void; let entered!: () => void; let settled = false; const registrationWaitEntered = new Promise<void>(resolve => entered = resolve); const registrationReady = new Promise<void>(resolve => release = resolve); extensionService.whenInstalledExtensionsRegistered = () => { entered(); return registrationReady; }; roots(files); files.dir('/markerless'); for (const path of ['/bundle', '/bundle/bundled', '/plugin', '/plugin/.codex-plugin', '/plugin/skills', '/plugin/skills/plug']) files.dir(path); files.put('/bundle/bundled/SKILL.md', skill('bundled')); files.put('/plugin/.codex-plugin/plugin.json', JSON.stringify({ name: 'canonical-plugin', skills: './skills/', extra: 'allowed' })); files.put('/plugin/skills/plug/SKILL.md', skill('plug')); const remote = URI.parse('vscode-remote://ssh-remote+test/plugin'); files.dir(remote.toString()); for (const path of ['/.codex-plugin', '/skills', '/skills/remote']) files.dir(`${remote}${path}`); files.put(`${remote}/.codex-plugin/plugin.json`, JSON.stringify({ name: 'remote-plugin', skills: './skills/' })); files.put(`${remote}/skills/remote/SKILL.md`, skill('remote')); extensions.push({ identifier: { value: 'publisher.any-id' }, extensionLocation: uri('/plugin') }, { identifier: { value: 'generic.markerless' }, extensionLocation: uri('/markerless') }, { identifier: { value: 'publisher.remote' }, extensionLocation: remote }); const service = new AgentSkillsService(files as never, { userHome: async () => uri('/home') } as never, { isWorkspaceTrusted: () => true } as never, extensionService as never, () => [uri('/bundle')]); const pending = service.getCatalog(undefined, undefined).then(value => { settled = true; return value; }); await registrationWaitEntered; assert.strictEqual(settled, false); release(); const catalog = await pending;
		assert.deepStrictEqual(catalog.skills.map(s => [s.identity, s.provenance.source, s.provenance.pluginName]), [['bundled', 'bundled', undefined], ['canonical-plugin:plug', 'plugin', 'canonical-plugin'], ['remote-plugin:remote', 'plugin', 'remote-plugin']]); assert.strictEqual(catalog.diagnostics.some(d => d.code === 'plugin_skill_manifest_invalid' && d.detail === 'file:///markerless'), false); extensions.splice(0); assert.strictEqual((await service.getCatalog(undefined, undefined)).skills.some(s => s.provenance.source === 'plugin'), false);
	});
	test('isolates invalid plugin manifests, roots, paths, and symlinks', async () => {
		const { files, service, extensions } = fixture(); roots(files); for (const root of ['/bad-json', '/bad-skills', '/bad-bom']) { files.dir(root); files.dir(`${root}/.codex-plugin`); } files.put('/bad-json/.codex-plugin/plugin.json', '{'); files.put('/bad-skills/.codex-plugin/plugin.json', JSON.stringify({ name: 'bad-skills', skills: './wrong/' })); files.put('/bad-bom/.codex-plugin/plugin.json', '\uFEFF' + JSON.stringify({ name: 'bad-bom', skills: './skills/' })); files.dir('/link', { link: true }); extensions.push({ extensionLocation: uri('/bad-json') }, { extensionLocation: uri('/bad-skills') }, { extensionLocation: uri('/bad-bom') }, { extensionLocation: uri('/link') }); const catalog = await service.getCatalog(undefined, undefined); assert.strictEqual(catalog.skills.length, 0); assert.deepStrictEqual(catalog.diagnostics.map(d => [d.code, d.detail]), [['plugin_skill_manifest_invalid', 'file:///bad-bom'], ['plugin_skill_manifest_invalid', 'file:///bad-json'], ['plugin_skill_manifest_invalid', 'file:///bad-skills'], ['plugin_skill_manifest_invalid', 'file:///link']]);
	});
	test('isolates invalid, unreadable, and symlink candidates with deterministic diagnostics', async () => {
		const { files, service } = fixture(); roots(files); for (const name of ['good', 'invalid', 'link', 'unreadable']) files.dir(`/home/.agents/skills/${name}`, name === 'link' ? { link: true } : {}); files.put('/home/.agents/skills/good/SKILL.md', skill('good')); files.put('/home/.agents/skills/invalid/SKILL.md', 'bad'); files.put('/home/.agents/skills/unreadable/SKILL.md', skill('unreadable'), { unreadable: true }); const catalog = await service.getCatalog(undefined, undefined); assert.deepStrictEqual(catalog.skills.map(s => s.identity), ['good']); assert.deepStrictEqual(catalog.diagnostics.map(d => d.code), ['skill_invalid_frontmatter', 'skill_candidate_invalid', 'skill_candidate_invalid']);
	});
	test('applies user then project name/path rules and reports invalid selectors', async () => {
		const { files, service } = fixture(); roots(files); files.dir('/home/.agents/skills/demo'); files.put('/home/.agents/skills/demo/SKILL.md', skill('demo')); const config: any = { skillConfigRules: [{ selector: { kind: 'name', value: 'demo' }, enabled: false }, { selector: { kind: 'path', value: 'file:///home/.agents/skills/demo/SKILL.md' }, enabled: true }], skillConfigDiagnostics: [{ code: 'skill_config_invalid', source: 'x' }] }; const catalog = await service.getCatalog(undefined, undefined, config); assert.strictEqual(catalog.skills.length, 1); assert.strictEqual(catalog.diagnostics[catalog.diagnostics.length - 1].code, 'skill_config_invalid'); assert.strictEqual((await service.getCatalog(undefined, undefined, { skillConfigRules: [{ selector: { kind: 'name', value: 'demo' }, enabled: false }] } as any)).skills.length, 0);
	});
	test('keeps optional metadata false while malformed optional metadata fails open', async () => {
		const { files, service } = fixture(); roots(files); for (const name of ['hidden', 'bad']) { files.dir(`/home/.agents/skills/${name}`); files.dir(`/home/.agents/skills/${name}/agents`); files.put(`/home/.agents/skills/${name}/SKILL.md`, skill(name)); } files.put('/home/.agents/skills/hidden/agents/openai.yaml', 'policy:\n  allow_implicit_invocation: false'); files.put('/home/.agents/skills/bad/agents/openai.yaml', '['); const catalog = await service.getCatalog(undefined, undefined); assert.deepStrictEqual(catalog.skills.map(s => [s.identity, s.implicit]), [['bad', true], ['hidden', false]]); assert.strictEqual(catalog.diagnostics.some(d => d.code === 'skill_optional_metadata_invalid'), true);
	});
	test('reads exact UTF-8 bodies from first byte through trailing newline and isolates stale, unreadable, and invalid UTF-8', async () => {
		const { files, service } = fixture(); roots(files); files.dir('/home/.agents/skills/demo'); const body = skill('demo', 'first\n') + '\n'; files.put('/home/.agents/skills/demo/SKILL.md', body); const catalog = await service.getCatalog(undefined, undefined); const s = catalog.skills[0]; assert.strictEqual((await service.readSkillBody(s.provenance.skillRoot, s.bodyRevision)).body, body); files.put('/home/.agents/skills/demo/SKILL.md', skill('demo', 'changed')); assert.strictEqual((await service.readSkillBody(s.provenance.skillRoot, s.bodyRevision)).diagnostic!.code, 'skill_stale'); files.put('/home/.agents/skills/demo/SKILL.md', new Uint8Array([0xff])); assert.strictEqual((await service.readSkillBody(s.provenance.skillRoot, s.bodyRevision)).diagnostic!.code, 'skill_invalid_utf8');
	});
	test('reads only admitted relative resources and rejects missing, outside, encoded, and symlink resources without fallback', async () => {
		const { files, service } = fixture(); roots(files); for (const path of ['/home/.agents/skills/demo', '/home/.agents/skills/demo/docs']) files.dir(path); const selectedBody = skill('demo'); files.put('/home/.agents/skills/demo/SKILL.md', selectedBody); files.put('/home/.agents/skills/demo/docs/a.txt', 'resource'); files.put('/home/.agents/skills/demo/docs/link.txt', 'bad', { link: true }); const s = (await service.getCatalog(undefined, undefined)).skills[0]; const selection = { identity: s.identity, skillRoot: s.provenance.skillRoot, bodyRevision: s.bodyRevision, body: selectedBody }; const options = { maxResourceBytes: 1024, token: CancellationToken.None }; assert.strictEqual((await service.readSkillResource(selection, 'docs/a.txt', options)).body, 'resource'); for (const path of ['missing.txt', '../x', 'docs%2fa.txt', 'docs/link.txt']) assert.notStrictEqual((await service.readSkillResource(selection, path, options)).body, 'resource'); assert.strictEqual((await service.readSkillBody(s.provenance.skillRoot, s.bodyRevision)).body!.includes('demo'), true);
	});
});
