import * as assert from 'assert';
import { URI } from '../../../../../base/common/uri.js';
import { ChatThreadService } from '../../browser/chatThreadService.js';
import { createSkillCatalog } from '../../common/agentSkills.js';
import { projectAgentConfig, resolveAgentInstructions, stableAgentInstructionRevision } from '../../common/agentInstructions.js';

const instructionSnapshot = () => { const config = projectAgentConfig({ developerInstructions: 'developer' }, undefined, [{ uri: 'file:///home/.codex/config.toml', scope: 'user', status: 'loaded', projectedKeys: ['developer_instructions'] }], 'file:///workspace', 'file:///workspace'); const candidates: any[] = []; return resolveAgentInstructions(config, candidates, stableAgentInstructionRevision(config, candidates)); };

type Authority = Readonly<{ allowed: boolean; generation: number }>;
const runTool = (receiver: any, name: string, id: string, rawParams: Record<string, unknown>, options?: { authority?: Authority; install?: boolean }) => {
	const generation = receiver._agentControlGeneration.get('parent') ?? 0;
	const authority = options && Object.prototype.hasOwnProperty.call(options, 'authority') ? options.authority : Object.freeze({ allowed: true, generation });
	if (authority && options?.install !== false) receiver._agentDelegationAuthorityOfThread.set('parent', authority);
	return (ChatThreadService.prototype as any)._runToolCall.call(receiver, 'parent', name, id, 'spoofed-mcp', { preapproved: false, unvalidatedToolParams: rawParams }, { ownerProjectRoot: 'file:///workspace' }, authority);
};
const receiver = () => { const messages: any[] = []; const calls: string[] = []; return { messages, calls, value: { state: { allThreads: { parent: {} }, currentThreadId: 'parent' }, streamState: {}, _agentInstructionSessionOfThread: new Map(), _instructionTurnOfThread: new Map(), _agentControlGeneration: new Map(), _agentDelegationAuthorityOfThread: new Map(), _agentSubagentService: { spawn: async () => { calls.push('spawn'); return { id: 'child', status: 'queued' }; }, wait: async () => { calls.push('wait'); return { id: 'child', status: 'running', deliverSummary: false }; }, interrupt: () => { calls.push('interrupt'); return { id: 'child', status: 'cancelled' }; }, forgetParent: (id: string) => calls.push(`forget:${id}`) }, _toolsService: { validateParams: new Proxy({}, { get() { throw new Error('builtin lookup'); } }) }, _mcpService: { getMCPTools() { throw new Error('MCP lookup'); } }, _addMessageToThread: (_: string, message: any) => messages.push(message), openNewThread() { }, _onDidChangeCurrentThread: { fire() { } } } }; };

suite('Void agent subagent Chat runtime routing', () => {
	test('routes controls before builtin/MCP and preserves the parent tool id', async () => { const fixture = receiver(); await runTool(fixture.value, 'spawn_agent', 'provider-tool-id', { message: 'inspect' }); assert.deepStrictEqual(fixture.calls, ['spawn']); assert.strictEqual(fixture.messages.length, 1); assert.strictEqual(fixture.messages[0].id, 'provider-tool-id'); assert.strictEqual(fixture.messages[0].mcpServerName, undefined); });
	test('fails closed without exact current authority and rejects unknown fields before state', async () => {
		const fixture = receiver();
		await runTool(fixture.value, 'spawn_agent', 'absent-id', { message: 'inspect' }, { authority: undefined, install: false });
		assert.deepStrictEqual(fixture.calls, []); assert.ok(/agent_delegation_not_authorized/.test(fixture.messages.pop().content));
		fixture.value._agentControlGeneration.set('parent', 1);
		const stale = Object.freeze({ allowed: true, generation: 0 });
		await runTool(fixture.value, 'spawn_agent', 'stale-id', { message: 'inspect' }, { authority: stale });
		assert.deepStrictEqual(fixture.calls, []); assert.ok(/agent_delegation_not_authorized/.test(fixture.messages.pop().content));
		await runTool(fixture.value, 'spawn_agent', 'bad-id', { message: 'inspect', model: 'override' });
		assert.deepStrictEqual(fixture.calls, []); assert.strictEqual(fixture.messages[0].type, 'invalid_params'); assert.strictEqual(fixture.messages[0].id, 'bad-id');
	});
	test('generation drift and reset during deferred wait drop every late tool result', async () => {
		const fixture = receiver(); let release!: () => void; fixture.value._agentSubagentService.wait = async () => { fixture.calls.push('wait'); await new Promise<void>(resolve => release = resolve); return { id: 'child', status: 'completed', deliverSummary: true }; }; const pending = runTool(fixture.value, 'wait_agent', 'wait-id', { timeout_ms: 30000 }); await Promise.resolve(); fixture.value._agentControlGeneration.set('parent', 1); release(); assert.deepStrictEqual(await pending, { interrupted: true }); assert.deepStrictEqual(fixture.messages, []);
		const resetFixture = receiver(); let releaseReset!: () => void; resetFixture.value._agentSubagentService.wait = async () => { resetFixture.calls.push('wait'); await new Promise<void>(resolve => releaseReset = resolve); return { id: 'child', status: 'completed', deliverSummary: true }; }; const resetPending = runTool(resetFixture.value, 'wait_agent', 'reset-wait-id', { timeout_ms: 30000 }); await Promise.resolve(); ChatThreadService.prototype.resetState.call(resetFixture.value); releaseReset(); assert.deepStrictEqual(await resetPending, { interrupted: true }); assert.deepStrictEqual(resetFixture.messages, []); assert.deepStrictEqual(resetFixture.calls, ['wait', 'forget:parent']); assert.strictEqual(resetFixture.value._agentDelegationAuthorityOfThread.size, 0); assert.strictEqual(resetFixture.value._agentControlGeneration.size, 0);
	});
	test('generation drift also drops a deferred control rejection', async () => { const fixture = receiver(); let reject!: (error: Error) => void; fixture.value._agentSubagentService.wait = () => { fixture.calls.push('wait'); return new Promise((_resolve, rejectPromise) => reject = rejectPromise); }; const pending = runTool(fixture.value, 'wait_agent', 'wait-error-id', { timeout_ms: 30000 }); await Promise.resolve(); fixture.value._agentControlGeneration.set('parent', 1); reject(new Error('late')); assert.deepStrictEqual(await pending, { interrupted: true }); assert.deepStrictEqual(fixture.messages, []); });
	test('Stop and destructive state replacement revoke and forget active children', async () => { let cancelled = 0; const forgotten: string[] = []; const fake: any = { _agentControlGeneration: new Map(), _agentDelegationAuthorityOfThread: new Map([['parent', Object.freeze({ allowed: true, generation: 0 })]]), _agentInstructionSessionOfThread: new Map(), _instructionTurnOfThread: new Map(), _agentSubagentService: { cancelParent: () => cancelled++, forgetParent: (id: string) => forgotten.push(id) }, state: { allThreads: { parent: {} }, currentThreadId: 'parent' }, streamState: {}, _setStreamState() { }, _restoreInstructionTurns() { }, _onDidChangeCurrentThread: { fire() { } } }; await ChatThreadService.prototype.abortRunning.call(fake, 'parent'); assert.strictEqual(cancelled, 1); assert.strictEqual(fake._agentControlGeneration.get('parent'), 1); assert.strictEqual(fake._agentDelegationAuthorityOfThread.has('parent'), false); fake._agentDelegationAuthorityOfThread.set('parent', Object.freeze({ allowed: true, generation: 1 })); ChatThreadService.prototype.dangerousSetState.call(fake, { allThreads: {}, currentThreadId: 'replacement' }); assert.deepStrictEqual(forgotten, ['parent']); assert.strictEqual(fake._agentDelegationAuthorityOfThread.size, 0); assert.strictEqual(fake._agentControlGeneration.size, 0); });
	test('an inert Agent selection adds only user authority and never invokes spawn', async () => {
		let spawned = 0; const messages: any[] = []; const authorities: Authority[] = []; const catalog = createSkillCatalog([]); const thread: any = { messages, state: { stagingSelections: [], mountedInfo: undefined }, filesWithUserChanges: new Set<string>() };
		const fake: any = { state: { allThreads: { parent: thread } }, streamState: {}, _agentControlGeneration: new Map(), _agentDelegationAuthorityOfThread: new Map(), _agentSubagentService: { cancelParent() { }, spawn() { spawned++; } }, _currentModelSelectionProps: () => ({ modelSelection: null, modelSelectionOptions: undefined }), _settingsService: { state: { overridesOfModel: {} } }, _beginInstructionTurn: async () => instructionSnapshot(), _purgeInstructionTurn() { }, _workspaceContextService: { getWorkspace: () => ({ folders: [{ uri: URI.parse('file:///workspace') }] }) }, _workspaceTrustManagementService: { isWorkspaceTrusted: () => true }, _agentSkillsService: { getCatalog: async () => catalog, readSkillBody: async () => ({}) }, _directoryStringService: {}, _fileService: {}, _rememberInstructionTurn() { }, _addMessageToThread: (_: string, message: any) => messages.push(message), _runChatAgent: async ({ agentDelegationAuthority }: any) => { authorities.push(agentDelegationAuthority); }, _wrapRunAgentToNotify: (promise: Promise<void>) => promise };
		await (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse.call(fake, { userMessage: 'inspect', _chatSelections: [{ type: 'Agent', label: 'Void application-level read-only', state: undefined }], threadId: 'parent' });
		await (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse.call(fake, { userMessage: 'plain', _chatSelections: [], threadId: 'parent' });
		await (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse.call(fake, { userMessage: 'malformed', _chatSelections: [{ type: 'Agent', label: 'Agent', state: undefined } as any], threadId: 'parent' });
		assert.strictEqual(spawned, 0); assert.strictEqual(messages.length, 3); assert.ok(messages[0].content.includes('no child has launched')); assert.ok(messages[0].content.includes('Call spawn_agent')); assert.strictEqual(messages[1].content.includes('spawn_agent'), false); assert.strictEqual(messages[2].content.includes('spawn_agent'), false);
		assert.deepStrictEqual(authorities.map(authority => authority.allowed), [true, false, false]); assert.ok(authorities[0].generation < authorities[1].generation && authorities[1].generation < authorities[2].generation); assert.strictEqual(fake._agentDelegationAuthorityOfThread.get('parent'), authorities[2]);
	});
});
