import assert from 'assert';
import { URI } from '../../../../../base/common/uri.js';
import { ChatThreadService } from '../../browser/chatThreadService.js';
import { ConvertToLLMMessageService, trimProtectedMutableContent } from '../../browser/convertToLLMMessageService.js';
import { createAgentRuntimeTurnSnapshot, createSkillCatalog, runtimeModelFingerprint, skillAdvertisement } from '../../common/agentSkills.js';
import { projectAgentConfig, resolveAgentInstructions, stableAgentInstructionRevision } from '../../common/agentInstructions.js';

const bytes = (value: string) => new TextEncoder().encode(value);
const skillText = (name: string) => `---\nname: ${name}\ndescription: ${name}\n---\n---frontmatter-${name}\nbody-${name}\n`;
const instructions = () => { const config = projectAgentConfig({ developerInstructions: 'developer' }, undefined, [{ uri: 'file:///home/.codex/config.toml', scope: 'user', status: 'loaded', projectedKeys: ['developer_instructions'] }], 'file:///workspace', 'file:///workspace'); const candidates = [{ uri: 'file:///workspace/AGENTS.md', outcome: Object.freeze({ status: 'bytes' as const, bytes: bytes('agents') }) }]; return resolveAgentInstructions(config, candidates, stableAgentInstructionRevision(config, candidates)); };
const catalog = () => createSkillCatalog(['one', 'two'].map((name, rank) => ({ source: 'user' as const, rank, root: 'file:///home', skillRoot: `file:///home/${name}`, directoryName: name, bytes: bytes(skillText(name)) })));
const runtime = (selected = ['one'], window = 10000) => { const value = catalog(); return createAgentRuntimeTurnSnapshot(instructions(), value, skillAdvertisement(value, window), selected.map(name => { const skill = value.skills.find(item => item.identity === name)!; const body = new TextDecoder().decode((['one', 'two'].map((n, rank) => ({ n, rank })).find(item => item.n === name) ? bytes(`---\nname: ${name}\ndescription: ${name}\n---\n---frontmatter-${name}\nbody-${name}\n`) : bytes(''))); return { identity: name, skillRoot: skill.provenance.skillRoot, bodyRevision: skill.bodyRevision, body }; }), { hasModel: true as const, providerName: 'openAI', modelName: 'gpt-4.1', contextWindow: window, reservedOutputTokens: 10, modelSelectionOptions: { reasoningEnabled: true }, selectedModelOverrides: { temperature: .2 } }, true); };

suite('Agent Skills runtime paths', () => {
	test('parses typed @ before raw $ identity, dedupes final selections, and reads all bodies before history or provider work', async () => {
		const value = catalog(); const one = value.skills[0]; const typed: any = { type: 'Skill', identity: 'one', catalogRevision: value.revision, bodyRevision: one.bodyRevision, skillRoot: one.provenance.skillRoot, description: one.description }; const thread: any = { messages: [], state: { stagingSelections: [typed] }, filesWithUserChanges: new Set<string>() }; const events: string[] = []; let captured: any;
		const receiver: any = { state: { allThreads: { task: thread }, overridesOfModel: {} }, streamState: {}, _settingsService: { state: { overridesOfModel: { openAI: { 'gpt-4.1': {} } } } }, _currentModelSelectionProps: () => ({ modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' }, modelSelectionOptions: {} }), _beginInstructionTurn: async () => instructions(), _purgeInstructionTurn: () => events.push('purge'), _workspaceContextService: { getWorkspace: () => ({ folders: [{ uri: { toString: () => 'file:///workspace' } }] }) }, _workspaceTrustManagementService: { isWorkspaceTrusted: () => true }, _agentSkillsService: { getCatalog: async () => value, readSkillBody: async (root: string) => { const skill = value.skills.find(item => item.provenance.skillRoot === root)!; events.push(`read:${skill.identity}`); return { body: skillText(skill.identity) }; } }, _directoryStringService: {}, _fileService: {}, _rememberInstructionTurn: (_: string, snapshot: any) => { events.push('remember'); captured = snapshot; }, _addMessageToThread: (_: string, message: any) => { events.push('history'); thread.messages.push(message); }, _runChatAgent: (options: any) => { events.push('provider'); captured = options.instructionSnapshot; return Promise.resolve(); }, _wrapRunAgentToNotify: (promise: Promise<void>) => promise };
		receiver._agentControlGeneration = new Map<string, number>(); receiver._agentDelegationAuthorityOfThread = new Map(); receiver._agentSubagentService = { cancelParent() { } };
		const submit = (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse; await submit.call(receiver, { userMessage: '$two $one', _chatSelections: [typed], threadId: 'task' }); assert.deepStrictEqual(captured.selected.map((item: any) => item.identity), ['one', 'two']); assert.deepStrictEqual(events.filter(event => event.startsWith('read:')), ['read:one', 'read:two']); assert.strictEqual(events.indexOf('read:two') < events.indexOf('remember'), true); assert.strictEqual(events.indexOf('remember') < events.indexOf('history') && events.indexOf('history') < events.indexOf('provider'), true); assert.deepStrictEqual(thread.messages[0].selections.filter((item: any) => item.type === 'Skill').map((item: any) => item.identity), ['one', 'two']); assert.strictEqual(thread.messages[0].content.includes('body-one') || thread.messages[0].displayContent.includes('body-two'), false); assert.deepStrictEqual(captured.selected.map((item: any) => item.body), [skillText('one'), skillText('two')]);
	});
	test('rejects stale, unreadable, and oversized multi-selection admissions atomically before new history or provider work', async () => {
		const value = catalog(); const submit = (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse; for (const [selection, body, expected] of [[{ type: 'Skill', identity: 'one', catalogRevision: 'stale', bodyRevision: 'stale', skillRoot: 'file:///stale', description: 'one' }, undefined, 'skill_stale'], [{ type: 'Skill', identity: 'one', catalogRevision: value.revision, bodyRevision: value.skills[0].bodyRevision, skillRoot: value.skills[0].provenance.skillRoot, description: 'one' }, undefined, 'skill_body_unreadable'], [{ type: 'Skill', identity: 'one', catalogRevision: value.revision, bodyRevision: value.skills[0].bodyRevision, skillRoot: value.skills[0].provenance.skillRoot, description: 'one' }, skillText('one') + 'x'.repeat(1_100_000), 'skill_context_admission_failed']] as any[]) { const thread: any = { messages: [{ role: 'user', content: 'existing' }], state: { stagingSelections: [selection] }, filesWithUserChanges: new Set<string>() }; let purges = 0, reads = 0, remembered = 0, runs = 0; const receiver: any = { state: { allThreads: { task: thread }, overridesOfModel: {} }, streamState: {}, _settingsService: { state: { overridesOfModel: { openAI: { 'gpt-4.1': {} } } } }, _currentModelSelectionProps: () => ({ modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' }, modelSelectionOptions: {} }), _beginInstructionTurn: async () => instructions(), _purgeInstructionTurn: () => purges++, _workspaceContextService: { getWorkspace: () => ({ folders: [{ uri: { toString: () => 'file:///workspace' } }] }) }, _workspaceTrustManagementService: { isWorkspaceTrusted: () => true }, _agentSkillsService: { getCatalog: async () => value, readSkillBody: async () => { reads++; return body === undefined ? { diagnostic: { code: 'skill_body_unreadable' } } : { body }; } }, _directoryStringService: {}, _fileService: {}, _rememberInstructionTurn: () => remembered++, _addMessageToThread: () => { throw new Error('history'); }, _runChatAgent: () => { runs++; return Promise.resolve(); }, _wrapRunAgentToNotify: () => { }, _agentControlGeneration: new Map<string, number>(), _agentDelegationAuthorityOfThread: new Map(), _agentSubagentService: { cancelParent() { } } }; await assert.rejects(() => submit.call(receiver, { userMessage: 'new', _chatSelections: [selection], threadId: 'task' }), new RegExp(expected)); assert.strictEqual(purges, 1); assert.strictEqual(remembered, 0); assert.strictEqual(runs, 0); assert.strictEqual(thread.messages.length, 1); if (expected === 'skill_stale') assert.strictEqual(reads, 0); }
		const one = value.skills[0]; const typed: any = { type: 'Skill', identity: 'one', catalogRevision: value.revision, bodyRevision: one.bodyRevision, skillRoot: one.provenance.skillRoot, description: one.description }; const file: any = { type: 'File', uri: URI.parse('file:///workspace/file.txt'), language: 'plaintext', state: { wasAddedAsCurrentFile: false } }; const existing: any = { role: 'user', content: 'existing' }; const thread: any = { messages: [existing], state: { stagingSelections: [typed, file] }, filesWithUserChanges: new Set<string>() }; let owner = 'file:///workspace', trusted = true, purges = 0, remembered = 0, history = 0, provider = 0; let releaseRead!: () => void; let enteredRead!: () => void; const readEntered = new Promise<void>(resolve => enteredRead = resolve); const readReady = new Promise<void>(resolve => releaseRead = resolve);
		const receiver: any = { state: { allThreads: { task: thread }, overridesOfModel: {} }, streamState: {}, _settingsService: { state: { overridesOfModel: { openAI: { 'gpt-4.1': {} } } } }, _currentModelSelectionProps: () => ({ modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' }, modelSelectionOptions: {} }), _beginInstructionTurn: async () => instructions(), _purgeInstructionTurn: () => purges++, _workspaceContextService: { getWorkspace: () => ({ folders: [{ uri: { toString: () => owner } }] }) }, _workspaceTrustManagementService: { isWorkspaceTrusted: () => trusted }, _agentSkillsService: { getCatalog: async () => value, readSkillBody: async () => ({ body: skillText('one') }) }, _directoryStringService: {}, _fileService: { readFile: async () => { enteredRead(); await readReady; return { value: { toString: () => 'file body' } }; } }, _rememberInstructionTurn: () => remembered++, _addMessageToThread: () => history++, _runChatAgent: () => { provider++; return Promise.resolve(); }, _wrapRunAgentToNotify: (promise: Promise<void>) => promise };
		receiver._agentControlGeneration = new Map<string, number>(); receiver._agentDelegationAuthorityOfThread = new Map(); receiver._agentSubagentService = { cancelParent() { } };
		const pending = submit.call(receiver, { userMessage: 'new', _chatSelections: [typed, file], threadId: 'task' }); await readEntered; owner = 'file:///workspace-b'; trusted = false; releaseRead(); await assert.rejects(pending, /skill_owner_or_trust_changed/); assert.strictEqual(purges, 2); assert.strictEqual(remembered, 0); assert.strictEqual(history, 0); assert.strictEqual(provider, 0); assert.strictEqual(thread.messages.length, 1); assert.strictEqual(thread.messages[0], existing);
	});
	test('preserves exact frontmatter and trailing-newline bodies while metadata-only advertisement is separate from user content', async () => {
		const snapshot = runtime(['one'], 10000); const converter = new ConvertToLLMMessageService({ getModels: () => [] } as never, { getWorkspace: () => ({ folders: [] }) } as never, { activeEditor: undefined } as never, { getAllDirectoriesStr: async () => '' } as never, { listPersistentTerminalIds: () => [] } as never, { state: { overridesOfModel: {}, globalSettings: {}, optionsOfModelSelection: {} } } as never, { getMCPTools: () => [] } as never); (converter as any)._generateChatMessagesSystemMessage = async () => 'generated'; const result = await converter.prepareLLMChatMessages({ chatMessages: [{ role: 'user', content: 'hello' }] as never, chatMode: 'agent' as never, modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' } as never, instructionSnapshot: snapshot }); const authority = result.messages.filter((message: any) => message.role === 'developer').map((message: any) => message.content).join('\n'); assert.strictEqual(snapshot.selected[0].body, skillText('one')); assert.strictEqual(snapshot.selected[0].body.endsWith('\n'), true); assert.strictEqual(authority.split(skillText('one')).length - 1, 1); assert.strictEqual(authority.includes(snapshot.advertisement.text), true); assert.strictEqual(snapshot.advertisement.text.includes('body-one'), false); assert.strictEqual(snapshot.advertisement.text.includes('identity=one'), true); assert.strictEqual(result.messages.filter((message: any) => message.role === 'user').some((message: any) => message.content.includes('body-one') || message.content.includes('---frontmatter-one')), false);
	});
	test('keeps one strict v2 snapshot through retry, tool loops, and persisted pending approval', async () => {
		const snapshot = Object.freeze(runtime(['one'])); const thread: any = { messages: [{ role: 'user', content: 'start' }], state: {}, filesWithUserChanges: new Set<string>() }; const prepared: unknown[][] = []; const receivedSnapshots: unknown[] = []; const converterAuthorities: boolean[] = []; const sent: unknown[] = []; const sendAuthorities: boolean[] = []; const toolSnapshots: unknown[] = []; const toolAuthorities: unknown[] = []; const streamState: any = {}; let preparation = 0, sends = 0;
		const authority = Object.freeze({ allowed: true, generation: 7 });
		const receiver: any = { state: { allThreads: { task: thread }, overridesOfModel: {} }, streamState, _agentControlGeneration: new Map([['task', 7]]), _agentDelegationAuthorityOfThread: new Map([['task', authority]]), _settingsService: { state: { globalSettings: { chatMode: 'agent' }, overridesOfModel: {} } }, _setStreamState: (threadId: string, value: any) => streamState[threadId] = value, _convertToLLMMessagesService: { prepareLLMChatMessages: async ({ chatMessages, instructionSnapshot, agentDelegationAllowed }: any) => { assert.strictEqual(chatMessages, thread.messages); receivedSnapshots.push(instructionSnapshot); converterAuthorities.push(agentDelegationAllowed); const messages = [{ role: 'user', content: `prepared-${preparation++}` }]; prepared.push(messages); return { messages, separateSystemMessage: undefined }; } }, _llmMessageService: { sendLLMMessage: (options: any) => { sent.push(options.messages); sendAuthorities.push(options.agentDelegationAllowed); sends++; if (sends === 1) void options.onError({ message: 'transient', fullError: null }); else if (sends === 2) void options.onFinalMessage({ fullText: 'tool', fullReasoning: '', toolCall: { name: 'read_file', id: 'tool-1', rawParams: {} }, anthropicReasoning: null }); else void options.onFinalMessage({ fullText: 'done', fullReasoning: '', anthropicReasoning: null }); return `send-${sends}`; }, abort: () => { } }, _mcpService: { getMCPTools: () => [{ name: 'read_file', mcpServerName: 'local' }] }, _runToolCall: async (...args: any[]) => { toolSnapshots.push(args[5]); toolAuthorities.push(args[6]); return { awaitingUserApproval: false, interrupted: false }; }, _addMessageToThread: (_: string, message: any) => thread.messages.push(message), _metricsService: { capture: () => { } } };
		await (ChatThreadService.prototype as any)._runChatAgent.call(receiver, { threadId: 'task', modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' }, modelSelectionOptions: snapshot.model.hasModel ? snapshot.model.modelSelectionOptions : undefined, instructionSnapshot: snapshot, agentDelegationAuthority: authority });
		assert.strictEqual(sends, 3); assert.strictEqual(sent[0], sent[1]); assert.strictEqual(sent[0], prepared[0]); assert.strictEqual(sent[2], prepared[1]); assert.notStrictEqual(prepared[0], prepared[1]); assert.deepStrictEqual(receivedSnapshots, [snapshot, snapshot]); assert.deepStrictEqual(converterAuthorities, [true, true]); assert.deepStrictEqual(sendAuthorities, [true, true, true]); assert.deepStrictEqual(toolSnapshots, [snapshot]); assert.deepStrictEqual(toolAuthorities, [authority]); assert.strictEqual(snapshot.selected[0].body, skillText('one')); assert.strictEqual(Object.prototype.hasOwnProperty.call(snapshot, 'agentDelegationAllowed'), false);

		const approvalSnapshot = createAgentRuntimeTurnSnapshot(snapshot.instructions, snapshot.catalog, snapshot.advertisement, snapshot.selected, { hasModel: true, providerName: 'openAI', modelName: 'gpt-4.1', contextWindow: 10_000, reservedOutputTokens: 5_000, modelSelectionOptions: { reasoningEnabled: true }, selectedModelOverrides: { contextWindow: 10_000, reservedOutputTokenSpace: 10 } }, true); const persisted = JSON.parse(JSON.stringify(approvalSnapshot)); const pending: any = { role: 'tool', type: 'tool_request', name: 'read_file', params: {}, content: 'approval requested', result: null, id: 'tool-1', rawParams: {}, mcpServerName: undefined }; const approvalThread = (): any => ({ messages: [{ ...pending }], state: { stagingSelections: [], focusedMessageIdx: undefined, linksOfMessageIdx: {}, agentInstructionTurnSnapshot: persisted }, filesWithUserChanges: new Set<string>() });
		const approvalBase = (approvalThreadValue: any, resume: (options: any) => void): any => ({ _purgeInstructionTurn: () => { }, _workspaceContextService: { getWorkspace: () => ({ folders: [{ uri: { toString: () => 'file:///workspace' } }] }) }, _workspaceTrustManagementService: { isWorkspaceTrusted: () => true }, state: { allThreads: { task: approvalThreadValue } }, _runChatAgent: (options: any) => { resume(options); return Promise.resolve(); }, _updateLatestTool: () => { }, _setStreamState: () => { }, _wrapRunAgentToNotify: () => { }, _settingsService: { state: { overridesOfModel: { openAI: { 'gpt-4.1': { contextWindow: 10_000, reservedOutputTokenSpace: 10 } } } } }, _currentModelSelectionProps: () => ({ modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' }, modelSelectionOptions: { reasoningEnabled: true } }) });
		let sameProcessResumed: any; const liveAuthority = Object.freeze({ allowed: true, generation: 4 }); const sameProcessThread = approvalThread(); const sameProcessReceiver = { ...approvalBase(sameProcessThread, options => sameProcessResumed = options), _instructionTurnOfThread: new Map([['task', approvalSnapshot]]), _agentControlGeneration: new Map([['task', 4]]), _agentDelegationAuthorityOfThread: new Map([['task', liveAuthority]]) };
		ChatThreadService.prototype.approveLatestToolRequest.call(sameProcessReceiver as never, 'task'); assert.strictEqual(sameProcessResumed.agentDelegationAuthority, liveAuthority);
		let restartedResumed: any; const restartedThread = approvalThread(); const restartedReceiver = { ...approvalBase(restartedThread, options => restartedResumed = options), _instructionTurnOfThread: new Map(), _agentControlGeneration: new Map([['task', 4]]), _agentDelegationAuthorityOfThread: new Map([['task', liveAuthority]]) };
		(ChatThreadService.prototype as any)._restoreInstructionTurns.call(restartedReceiver, restartedReceiver.state.allThreads); const revived = restartedReceiver._instructionTurnOfThread.get('task'); ChatThreadService.prototype.approveLatestToolRequest.call(restartedReceiver, 'task'); assert.notStrictEqual(revived, persisted); assert.strictEqual(restartedResumed.instructionSnapshot, revived); assert.strictEqual(restartedResumed.agentDelegationAuthority, undefined); assert.deepStrictEqual(restartedResumed.modelSelection, { providerName: 'openAI', modelName: 'gpt-4.1' }); assert.strictEqual(restartedResumed.modelSelectionOptions, revived.model.modelSelectionOptions); assert.deepStrictEqual(revived.selected.map((item: any) => item.body), [skillText('one')]);
	});
	test('captures model options and overrides before awaiting catalog and skill bodies', async () => {
		const value = catalog(); const modelA: any = { providerName: 'openAI', modelName: 'gpt-4.1' }; const optionsA: any = { reasoningEnabled: true, reasoningEffort: 'high-A' }; const overridesA: any = { contextWindow: 10_001, reservedOutputTokenSpace: 10 }; const modelB: any = { providerName: 'openAI', modelName: 'gpt-4.1-mini' }; const optionsB: any = { reasoningEnabled: false, reasoningEffort: 'low-B' }; const overridesB: any = { contextWindow: 20_000, reservedOutputTokenSpace: 20 }; let current: any = { modelSelection: modelA, modelSelectionOptions: optionsA }; let resolveCatalog!: () => void; let catalogRequested!: () => void; const catalogReady = new Promise<void>(resolve => { resolveCatalog = resolve; }); const catalogStarted = new Promise<void>(resolve => { catalogRequested = resolve; }); const thread: any = { messages: [], state: { stagingSelections: [] }, filesWithUserChanges: new Set<string>() }; let remembered: any; let provider: any;
		const receiver: any = { state: { allThreads: { task: thread }, overridesOfModel: {} }, streamState: {}, _settingsService: { state: { overridesOfModel: { openAI: { 'gpt-4.1': overridesA } } } }, _currentModelSelectionProps: () => current, _beginInstructionTurn: async () => instructions(), _purgeInstructionTurn: () => { }, _workspaceContextService: { getWorkspace: () => ({ folders: [{ uri: { toString: () => 'file:///workspace' } }] }) }, _workspaceTrustManagementService: { isWorkspaceTrusted: () => true }, _agentSkillsService: { getCatalog: async () => { catalogRequested(); await catalogReady; return value; }, readSkillBody: async (root: string) => ({ body: skillText(value.skills.find(item => item.provenance.skillRoot === root)!.identity) }) }, _directoryStringService: {}, _fileService: {}, _rememberInstructionTurn: (_: string, snapshot: any) => remembered = snapshot, _addMessageToThread: (_: string, message: any) => thread.messages.push(message), _runChatAgent: (options: any) => { provider = options; return Promise.resolve(); }, _wrapRunAgentToNotify: (promise: Promise<void>) => promise };
		receiver._agentControlGeneration = new Map<string, number>(); receiver._agentDelegationAuthorityOfThread = new Map(); receiver._agentSubagentService = { cancelParent() { } };
		const submit = (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse; const pending = submit.call(receiver, { userMessage: '$one', threadId: 'task' }); await catalogStarted; current = { modelSelection: modelB, modelSelectionOptions: optionsB }; receiver._settingsService.state.overridesOfModel = { openAI: { 'gpt-4.1-mini': overridesB } }; resolveCatalog(); await pending;
		assert.strictEqual(remembered, provider.instructionSnapshot); assert.deepStrictEqual(provider.modelSelection, modelA); assert.strictEqual(provider.modelSelectionOptions, optionsA); assert.strictEqual(remembered.model.hasModel, true); assert.strictEqual(remembered.model.providerName, modelA.providerName); assert.strictEqual(remembered.model.modelName, modelA.modelName); assert.strictEqual(remembered.model.reservedOutputTokens, 5_001); assert.strictEqual(Number.isSafeInteger(remembered.model.reservedOutputTokens), true); assert.deepStrictEqual(remembered.model.modelSelectionOptions, optionsA); assert.deepStrictEqual(remembered.model.selectedModelOverrides, overridesA); assert.strictEqual(remembered.model.fingerprint, runtimeModelFingerprint({ providerName: modelA.providerName, modelName: modelA.modelName, contextWindow: remembered.model.contextWindow, reservedOutputTokens: remembered.model.reservedOutputTokens, modelSelectionOptions: optionsA, selectedModelOverrides: overridesA })); assert.strictEqual(remembered.selected[0].body, skillText('one')); assert.strictEqual(JSON.stringify(remembered).includes('"B"'), false); assert.strictEqual(JSON.stringify(provider).includes('"B"'), false);
	});
	test('fails closed for legacy and malformed persisted runtime metadata without changing thread state', () => {
		const v1Phase1Shape: any = { schemaVersion: 1, revision: 'phase1', instructions: { revision: 'phase1' }, selected: [{ identity: 'one' }], model: { hasModel: true, providerName: 'openAI', modelName: 'gpt-4.1' } }; const malformedV2: any = JSON.parse(JSON.stringify(runtime(['one']))); delete malformedV2.workspaceTrustedAtAdmission; malformedV2.revision = 'stale-revision';
		for (const persisted of [v1Phase1Shape, malformedV2]) { const message: any = { role: 'user', content: 'keep' }; const skill: any = { type: 'Skill', identity: 'one', catalogRevision: 'catalog', bodyRevision: 'body', skillRoot: 'file:///home/one', description: 'one' }; const links: any = { 0: [{ uri: 'file:///keep' }] }; const files = new Set<string>(['file:///keep']); const thread: any = { messages: [message], state: { stagingSelections: [skill], focusedMessageIdx: 0, linksOfMessageIdx: links, agentInstructionTurnSnapshot: persisted }, filesWithUserChanges: files }; const receiver: any = { _instructionTurnOfThread: new Map(), _workspaceContextService: { getWorkspace: () => ({ folders: [{ uri: { toString: () => 'file:///workspace' } }] }) }, _workspaceTrustManagementService: { isWorkspaceTrusted: () => true } };
			(ChatThreadService.prototype as any)._restoreInstructionTurns.call(receiver, { task: thread }); assert.strictEqual(thread.state.agentInstructionTurnSnapshot, undefined); assert.strictEqual(receiver._instructionTurnOfThread.size, 0); assert.strictEqual(thread.messages.length, 1); assert.strictEqual(thread.messages[0], message); assert.strictEqual(thread.state.stagingSelections[0], skill); assert.strictEqual(thread.state.focusedMessageIdx, 0); assert.strictEqual(thread.state.linksOfMessageIdx, links); assert.strictEqual(thread.filesWithUserChanges, files); }
	});
	test('routes protected authority only through Chat converter, trims mutable history, and rejects oversize authority', async () => {
		const converter = new ConvertToLLMMessageService({ getModels: () => [] } as never, { getWorkspace: () => ({ folders: [] }) } as never, { activeEditor: undefined } as never, { getAllDirectoriesStr: async () => '' } as never, { listPersistentTerminalIds: () => [] } as never, { state: { overridesOfModel: {}, globalSettings: {}, optionsOfModelSelection: { Chat: { openAI: { 'gpt-4.1': {} } }, 'Ctrl+K': { openAI: { 'gpt-4.1': {} } } } } } as never, { getMCPTools: () => [] } as never); (converter as any)._generateChatMessagesSystemMessage = async () => 'system'; const history = 'history'.repeat(1_000); const protectedResult = await converter.prepareLLMChatMessages({ chatMessages: [{ role: 'user', content: history }] as never, chatMode: 'agent' as never, modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' } as never, instructionSnapshot: runtime(['one'], 500) }); const authority = protectedResult.messages.filter((message: any) => message.role === 'developer').map((message: any) => message.content).join('\n'); const trimmedHistory = protectedResult.messages.filter((message: any) => message.role === 'user').map((message: any) => message.content).join('\n'); assert.strictEqual(authority.split(skillText('one')).length - 1, 1); assert.strictEqual(trimmedHistory.length < history.length, true); assert.strictEqual(trimProtectedMutableContent('abcdef', 1), 'a'); assert.strictEqual(trimProtectedMutableContent('abcdef', 2), 'ab'); assert.strictEqual(trimProtectedMutableContent('abcdef', 4), 'a...'); assert.strictEqual(authority.includes(skillText('one')), true); await assert.rejects(() => converter.prepareLLMChatMessages({ chatMessages: [{ role: 'user', content: history }] as never, chatMode: 'agent' as never, modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' } as never, instructionSnapshot: runtime(['one'], 5) }), /skill_context_admission_failed/); const simple = converter.prepareLLMSimpleMessages({ simpleMessages: [{ role: 'user', content: 'simple' }] as never, systemMessage: 'simple system', modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' } as never, featureName: 'Ctrl+K' as never }); const fim = converter.prepareFIMMessage({ messages: { prefix: 'a', suffix: 'b', stopTokens: [] } }); for (const result of [simple, fim]) { const serialized = JSON.stringify(result); assert.strictEqual(serialized.includes('body-one') || serialized.includes('---frontmatter-one') || serialized.includes('identity=one'), false); }
	});
});
