import * as assert from 'assert';
import { URI } from '../../../../../base/common/uri.js';
import { ChatThreadService } from '../../browser/chatThreadService.js';
import { createSkillCatalog } from '../../common/agentSkills.js';
import { projectAgentConfig, resolveAgentInstructions, stableAgentInstructionRevision } from '../../common/agentInstructions.js';

const instructionSnapshot = (limits?: { maxAcceptedChildren?: number; maxConcurrentThreadsPerSession?: number; maxDepth?: number }, diagnostics: any[] = []) => { const projectedKeys: any[] = ['developer_instructions']; if (limits || diagnostics.length) projectedKeys.push('agents'); if (limits?.maxAcceptedChildren !== undefined) projectedKeys.push('agents.max_accepted_children'); if (limits?.maxConcurrentThreadsPerSession !== undefined) projectedKeys.push('agents.max_concurrent_threads_per_session'); if (limits?.maxDepth !== undefined) projectedKeys.push('agents.max_depth'); const config = projectAgentConfig({ developerInstructions: 'developer', ...(limits?.maxAcceptedChildren === undefined ? {} : { agentMaxAcceptedChildren: limits.maxAcceptedChildren }), ...(limits?.maxConcurrentThreadsPerSession === undefined ? {} : { agentMaxConcurrentThreadsPerSession: limits.maxConcurrentThreadsPerSession }), ...(limits?.maxDepth === undefined ? {} : { agentMaxDepth: limits.maxDepth }), ...(diagnostics.length ? { agentDelegationLimitDiagnostics: diagnostics, agentsConfigPresent: true } : {}) }, undefined, [{ uri: 'file:///home/.codex/config.toml', scope: 'user', status: 'loaded', projectedKeys }], 'file:///workspace', 'file:///workspace'); const candidates: any[] = []; return resolveAgentInstructions(config, candidates, stableAgentInstructionRevision(config, candidates)); };

type Authority = Readonly<{ allowed: boolean; generation: number; limits?: Readonly<{ maxAcceptedChildren: number; maxConcurrentThreadsPerSession: number; maxDepth: number }> }>;
type AdmissionRole = Readonly<{ identity: string; revision: string; description: string }>;
type AdmissionCatalog = Readonly<{ revision: string; agents: readonly AdmissionRole[]; diagnostics: readonly unknown[] }>;
type AdmissionMessage = { content?: string; displayContent?: string };
type AdmissionStream = { isRunning?: string; llmInfo?: { displayContentSoFar: string; reasoningSoFar: string; toolCallSoFar: null }; interrupt?: Promise<() => void>; error?: { message: string; fullError: Error | null } };
type AdmissionSelection = Readonly<{ type: 'Agent'; label: 'Void application-level read-only'; agentType: string; catalogRevision: string; roleRevision: string; state: undefined }>;
interface AdmissionLifecycleAdapter {
	_addUserMessageAndStreamResponse(this: unknown, options: { userMessage: string; _chatSelections: readonly AdmissionSelection[]; threadId: string }): Promise<boolean>;
	_revokeAgentDelegation(this: unknown, threadId: string, forget?: boolean): void;
}
const admissionLifecycle = ChatThreadService.prototype as unknown as AdmissionLifecycleAdapter;
const runTool = (receiver: any, name: string, id: string, rawParams: Record<string, unknown>, options?: { authority?: Authority; install?: boolean }) => {
	const generation = receiver._agentControlGeneration.get('parent') ?? 0;
	const authority = options && Object.prototype.hasOwnProperty.call(options, 'authority') ? options.authority : Object.freeze({ allowed: true, generation });
	if (authority && options?.install !== false) receiver._agentDelegationAuthorityOfThread.set('parent', authority);
	return (ChatThreadService.prototype as any)._runToolCall.call(receiver, 'parent', name, id, 'spoofed-mcp', { preapproved: false, unvalidatedToolParams: rawParams }, { ownerProjectRoot: 'file:///workspace' }, authority, false, undefined, () => true);
};
const bindApprovals = (value: any) => { value._childToolApprovals ??= new Map(); value._onDidChangeChildToolApprovals ??= { fire() { } }; for (const name of ['_cancelChildToolApproval', '_cancelChildToolApprovalsForParent', '_decideChildToolApproval', 'getChildToolApprovals'] as const) value[name] ??= (...args: any[]) => (ChatThreadService.prototype as any)[name].call(value, ...args); };
const revoke = function (this: any, threadId: string, forget = false) { this._parentRunTokenOfThread ??= new Map(); this._toolsService ??= {}; this._toolsService.invalidateReadReceipts ??= (_threadId: string) => { }; bindApprovals(this); return (ChatThreadService.prototype as any)._revokeAgentDelegation.call(this, threadId, forget); };
const receiver = () => { const messages: any[] = []; const calls: any[] = []; return { messages, calls, value: { state: { allThreads: { parent: {} }, currentThreadId: 'parent' }, streamState: {}, _agentInstructionSessionOfThread: new Map(), _instructionTurnOfThread: new Map(), _agentControlGeneration: new Map(), _agentDelegationAuthorityOfThread: new Map(), _transientComposerDraftOfThread: new Map(), _revokeAgentDelegation: revoke, _agentCustomAgentService: { getCatalog: async () => ({ revision: 'roles', agents: [], diagnostics: [] }) }, _agentSubagentService: { spawn: async (...args: any[]) => { calls.push(['spawn', args]); return { id: 'child', status: 'queued' }; }, wait: async () => { calls.push(['wait']); return { id: 'child', status: 'running', deliverSummary: false }; }, interrupt: () => { calls.push(['interrupt']); return { id: 'child', status: 'cancelled' }; }, forgetParent: (id: string) => calls.push([`forget:${id}`]) }, _toolsService: { invalidateReadReceipts(_threadId: string) { }, validateParams: new Proxy({}, { get() { throw new Error('builtin lookup'); } }) }, _mcpService: { getMCPTools() { throw new Error('MCP lookup'); } }, _addMessageToThread: (_: string, message: any) => messages.push(message), openNewThread() { }, _onDidChangeCurrentThread: { fire() { } } } }; };

suite('Void agent subagent Chat runtime routing', () => {
	test('generic and named Agent selections replace each other with the latest exact intent', () => {
		let selections: any[] = []; const receiver: any = { getCurrentFocusedMessageIdx: () => undefined, getCurrentThreadState: () => ({ stagingSelections: selections }), setCurrentThreadState: ({ stagingSelections }: any) => selections = stagingSelections };
		const generic = { type: 'Agent', label: 'Void application-level read-only', state: undefined } as const; const named = { type: 'Agent', label: 'Void application-level read-only', agentType: 'reader', catalogRevision: 'catalog', roleRevision: 'role', state: undefined } as const;
		ChatThreadService.prototype.addNewStagingSelection.call(receiver, generic); ChatThreadService.prototype.addNewStagingSelection.call(receiver, named); assert.strictEqual(selections.length, 1); assert.strictEqual(selections[0].agentType, 'reader');
		selections = []; ChatThreadService.prototype.addNewStagingSelection.call(receiver, named); ChatThreadService.prototype.addNewStagingSelection.call(receiver, generic); assert.strictEqual(selections.length, 1); assert.strictEqual(selections[0].agentType, undefined);
	});
	test('routes controls before builtin/MCP and preserves the parent tool id', async () => { const fixture = receiver(); await runTool(fixture.value, 'spawn_agent', 'provider-tool-id', { message: 'inspect' }); assert.strictEqual(fixture.calls[0][0], 'spawn'); assert.strictEqual(fixture.calls[0][1][3], undefined); assert.strictEqual(fixture.messages.length, 1); assert.strictEqual(fixture.messages[0].id, 'provider-tool-id'); assert.strictEqual(fixture.messages[0].mcpServerName, undefined); });
	test('fails closed without exact current authority and rejects unknown fields before state', async () => {
		const fixture = receiver();
		await runTool(fixture.value, 'spawn_agent', 'absent-id', { message: 'inspect' }, { authority: undefined, install: false });
		assert.deepStrictEqual(fixture.calls, []); assert.ok(/agent_delegation_not_authorized/.test(fixture.messages.pop().content));
		fixture.value._agentControlGeneration.set('parent', 1);
		const stale = Object.freeze({ allowed: true, generation: 0 });
		await runTool(fixture.value, 'spawn_agent', 'stale-id', { message: 'inspect' }, { authority: stale });
		assert.deepStrictEqual(fixture.calls, []); assert.ok(/agent_delegation_not_authorized/.test(fixture.messages.pop().content));
		await runTool(fixture.value, 'spawn_agent', 'bad-id', { message: 'inspect', model: 'override' });
		assert.deepStrictEqual(fixture.calls, []); assert.strictEqual(fixture.messages[0].type, 'invalid_params'); assert.strictEqual(fixture.messages[0].id, 'bad-id');
	});
	test('generation drift and reset during deferred wait drop every late tool result', async () => {
		const fixture = receiver(); let release!: () => void; fixture.value._agentSubagentService.wait = async () => { fixture.calls.push('wait'); await new Promise<void>(resolve => release = resolve); return { id: 'child', status: 'completed', deliverSummary: true }; }; const pending = runTool(fixture.value, 'wait_agent', 'wait-id', { timeout_ms: 30000 }); await Promise.resolve(); fixture.value._agentControlGeneration.set('parent', 1); release(); assert.deepStrictEqual(await pending, { interrupted: true }); assert.deepStrictEqual(fixture.messages, []);
		const resetFixture = receiver(); let releaseReset!: () => void; resetFixture.value._agentSubagentService.wait = async () => { resetFixture.calls.push('wait'); await new Promise<void>(resolve => releaseReset = resolve); return { id: 'child', status: 'completed', deliverSummary: true }; }; const resetPending = runTool(resetFixture.value, 'wait_agent', 'reset-wait-id', { timeout_ms: 30000 }); await Promise.resolve(); ChatThreadService.prototype.resetState.call(resetFixture.value); releaseReset(); assert.deepStrictEqual(await resetPending, { interrupted: true }); assert.deepStrictEqual(resetFixture.messages, []); assert.deepStrictEqual(resetFixture.calls, ['wait', ['forget:parent']]); assert.strictEqual(resetFixture.value._agentDelegationAuthorityOfThread.size, 0); assert.strictEqual(resetFixture.value._agentControlGeneration.size, 0);
	});
	test('generation drift also drops a deferred control rejection', async () => { const fixture = receiver(); let reject!: (error: Error) => void; fixture.value._agentSubagentService.wait = () => { fixture.calls.push('wait'); return new Promise((_resolve, rejectPromise) => reject = rejectPromise); }; const pending = runTool(fixture.value, 'wait_agent', 'wait-error-id', { timeout_ms: 30000 }); await Promise.resolve(); fixture.value._agentControlGeneration.set('parent', 1); reject(new Error('late')); assert.deepStrictEqual(await pending, { interrupted: true }); assert.deepStrictEqual(fixture.messages, []); });
		test('Stop and destructive state replacement revoke and forget active children', async () => { let cancelled = 0; const forgotten: string[] = []; const fake: any = { _revokeAgentDelegation: revoke, _agentControlGeneration: new Map(), _agentDelegationAuthorityOfThread: new Map([['parent', Object.freeze({ allowed: true, generation: 0 })]]), _agentInstructionSessionOfThread: new Map(), _instructionTurnOfThread: new Map(), _transientComposerDraftOfThread: new Map(), _agentSubagentService: { cancelParent: () => cancelled++, forgetParent: (id: string) => forgotten.push(id) }, _toolsService: { invalidateReadReceipts(_threadId: string) { } }, state: { allThreads: { parent: {} }, currentThreadId: 'parent' }, streamState: {}, _setStreamState() { }, _restoreInstructionTurns() { }, _onDidChangeCurrentThread: { fire() { } } }; await ChatThreadService.prototype.abortRunning.call(fake, 'parent'); assert.strictEqual(cancelled, 1); assert.strictEqual(fake._agentControlGeneration.get('parent'), 1); assert.strictEqual(fake._agentDelegationAuthorityOfThread.has('parent'), false); fake._agentDelegationAuthorityOfThread.set('parent', Object.freeze({ allowed: true, generation: 1 })); ChatThreadService.prototype.dangerousSetState.call(fake, { allThreads: {}, currentThreadId: 'replacement' }); assert.deepStrictEqual(forgotten, ['parent']); assert.strictEqual(fake._agentDelegationAuthorityOfThread.size, 0); assert.strictEqual(fake._agentControlGeneration.size, 0); });
	test('central revoke is one-shot for purge, delete, replacement, reset, and dispose; switching tasks is non-destructive', () => {
		const make = (threads: Record<string, any> = { parent: { state: {} }, other: { state: {} } }) => {
			const cancelled: string[] = [], forgotten: string[] = [];
			const value: any = { _revokeAgentDelegation: revoke, _agentControlGeneration: new Map([['parent', 4], ['other', 7]]), _agentDelegationAuthorityOfThread: new Map<string, Authority>([['parent', Object.freeze({ allowed: true, generation: 4 })], ['other', Object.freeze({ allowed: true, generation: 7 })]]), _agentInstructionSessionOfThread: new Map(Object.keys(threads).map(id => [id, {}])), _instructionTurnOfThread: new Map(Object.keys(threads).map(id => [id, {}])), _transientComposerDraftOfThread: new Map(), clearTransientComposerDraft(threadId: string) { this._transientComposerDraftOfThread.delete(threadId); }, _agentSubagentService: { cancelParent: (id: string) => cancelled.push(id), forgetParent: (id: string) => forgotten.push(id) }, _toolsService: { invalidateReadReceipts() { } }, _storeAllThreads() { }, _setState(patch: any) { this.state = { ...this.state, ...patch }; }, _restoreInstructionTurns() { }, _onDidChangeCurrentThread: { fire() { } }, _store: { dispose() { } }, openNewThread() { }, state: { allThreads: threads, currentThreadId: 'parent' } };
			return { value, cancelled, forgotten };
		};
		const switched = make(); ChatThreadService.prototype.switchToThread.call(switched.value, 'other'); assert.deepStrictEqual(switched.cancelled, []); assert.deepStrictEqual(switched.forgotten, []); assert.strictEqual(switched.value.state.currentThreadId, 'other');
		const purged = make({ parent: { state: {} } }); (ChatThreadService.prototype as any)._purgeInstructionTurn.call(purged.value, 'parent'); assert.deepStrictEqual(purged.cancelled, ['parent']); assert.strictEqual(purged.value._agentControlGeneration.get('parent'), 5);
		const deleted = make({ parent: { state: {} } }); ChatThreadService.prototype.deleteThread.call(deleted.value, 'parent'); assert.deepStrictEqual(deleted.forgotten, ['parent']); assert.strictEqual(deleted.value._agentControlGeneration.has('parent'), false);
		const replaced = make({ parent: { state: {} }, other: { state: {} } }); ChatThreadService.prototype.dangerousSetState.call(replaced.value, { allThreads: {}, currentThreadId: 'replacement' }); assert.deepStrictEqual(replaced.forgotten.sort(), ['other', 'parent']); assert.strictEqual(replaced.value._agentControlGeneration.size, 0);
		const reset = make({ parent: { state: {} }, other: { state: {} } }); ChatThreadService.prototype.resetState.call(reset.value); assert.deepStrictEqual(reset.forgotten.sort(), ['other', 'parent']); assert.strictEqual(reset.value._agentControlGeneration.size, 0);
		const disposed = make({ parent: { state: {} }, other: { state: {} } }); ChatThreadService.prototype.dispose.call(disposed.value); assert.deepStrictEqual(disposed.forgotten.sort(), ['other', 'parent']); assert.strictEqual(disposed.value._agentControlGeneration.size, 0);
	});
	test('native Agent routes expose generic controls without a marker, freeze configured limits, and never auto-spawn', async () => {
		let spawned = 0; const messages: any[] = []; const warnings: any[] = []; const authorities: Authority[] = []; const catalog = createSkillCatalog([]); const thread: any = { messages, state: { stagingSelections: [], mountedInfo: undefined }, filesWithUserChanges: new Set<string>() };
		const fake: any = { state: { allThreads: { parent: thread } }, streamState: {}, _agentControlGeneration: new Map(), _agentDelegationAuthorityOfThread: new Map(), _agentSubagentService: { cancelParent() { }, forgetParent() { }, spawn() { spawned++; } }, _agentCustomAgentService: { getCatalog: async () => ({ revision: 'roles', agents: [{ identity: 'project-reader', description: 'Project winner' }], diagnostics: [] }) }, _currentModelSelectionProps: () => ({ modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' }, modelSelectionOptions: {} }), _settingsService: { state: { globalSettings: { chatMode: 'agent' }, overridesOfModel: { openAI: { 'gpt-4.1': {} } } } }, _llmMessageService: { captureSettingsOfProvider: () => ({}) }, _beginInstructionTurn: async () => instructionSnapshot({ maxAcceptedChildren: 1, maxConcurrentThreadsPerSession: 1, maxDepth: 1 }, [{ source: 'user', reason: 'max_depth_invalid', code: 'agent_delegation_limits_invalid' }]), _purgeInstructionTurn() { }, _workspaceContextService: { getWorkspace: () => ({ folders: [{ uri: URI.parse('file:///workspace') }] }) }, _workspaceTrustManagementService: { isWorkspaceTrusted: () => true }, _agentSkillsService: { getCatalog: async () => catalog, readSkillBody: async () => ({}) }, _directoryStringService: {}, _fileService: {}, _notificationService: { notify: (warning: any) => warnings.push(warning) }, _rememberInstructionTurn() { }, _addMessageToThread: (_: string, message: any) => messages.push(message), _runChatAgent: async ({ agentDelegationAuthority }: any) => { authorities.push(agentDelegationAuthority); }, _wrapRunAgentToNotify: (promise: Promise<void>) => promise };
		fake._revokeAgentDelegation = revoke; fake._mcpService = { getMCPTools: () => [] };
		await (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse.call(fake, { userMessage: 'plain', _chatSelections: [], threadId: 'parent' });
		await (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse.call(fake, { userMessage: 'inspect', _chatSelections: [{ type: 'Agent', label: 'Void application-level read-only', state: undefined }], threadId: 'parent' });
		await (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse.call(fake, { userMessage: 'malformed', _chatSelections: [{ type: 'Agent', label: 'Agent', state: undefined } as any], threadId: 'parent' });
		const delegatedContent = messages.map(message => message.content).join('\n'); assert.strictEqual(spawned, 0); assert.strictEqual(messages.length, 3); assert.ok(delegatedContent.includes('project-reader')); assert.ok(delegatedContent.includes('spawn_agent')); assert.ok(delegatedContent.includes('up to 1')); assert.ok(delegatedContent.includes('1 running concurrently')); assert.ok(delegatedContent.includes('maximum depth 1')); assert.ok(delegatedContent.includes('wait_agent')); assert.strictEqual(messages[0].content.includes('spawn_agent'), false); assert.strictEqual(messages[1].content.includes('spawn_agent'), true); assert.strictEqual(messages[2].content.includes('spawn_agent'), false);
		assert.deepStrictEqual(authorities.map(authority => authority.allowed), [true, true, true]); assert.deepStrictEqual(authorities[0].limits, { maxAcceptedChildren: 1, maxConcurrentThreadsPerSession: 1, maxDepth: 1 }); assert.strictEqual(messages[0].content.includes('User delegation marker'), false); assert.ok(authorities[0].generation < authorities[1].generation && authorities[1].generation < authorities[2].generation); assert.strictEqual(fake._agentDelegationAuthorityOfThread.get('parent'), authorities[2]); assert.strictEqual(warnings.length, 3); assert.ok(warnings.every(warning => /safe limits: up to 1 children, 1 concurrent, depth 1/.test(warning.message))); assert.strictEqual(warnings.some(warning => /\.toml|file:\/\//.test(warning.message)), false);
	});
	test('a named Agent role is exact parent intent, never an automatic child', async () => {
		let spawned = 0; const messages: any[] = []; const authorities: any[] = []; const catalog = createSkillCatalog([]); const role = { identity: 'project-reader', revision: 'role-1', description: 'Project reader' };
		const fake: any = { state: { allThreads: { parent: { messages, state: { stagingSelections: [], mountedInfo: undefined }, filesWithUserChanges: new Set<string>() } } }, streamState: {}, _agentControlGeneration: new Map(), _agentDelegationAuthorityOfThread: new Map(), _agentSubagentService: { cancelParent() { }, forgetParent() { }, spawn() { spawned++; } }, _agentCustomAgentService: { getCatalog: async () => ({ revision: 'catalog-1', agents: [role], diagnostics: [] }) }, _currentModelSelectionProps: () => ({ modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' }, modelSelectionOptions: {} }), _settingsService: { state: { globalSettings: { chatMode: 'agent' }, overridesOfModel: { openAI: { 'gpt-4.1': {} } } } }, _llmMessageService: { captureSettingsOfProvider: () => ({}) }, _beginInstructionTurn: async () => instructionSnapshot(), _purgeInstructionTurn() { }, _workspaceContextService: { getWorkspace: () => ({ folders: [{ uri: URI.parse('file:///workspace') }] }) }, _workspaceTrustManagementService: { isWorkspaceTrusted: () => true }, _agentSkillsService: { getCatalog: async () => catalog, readSkillBody: async () => ({}) }, _directoryStringService: {}, _fileService: {}, _rememberInstructionTurn() { }, _addMessageToThread: (_: string, message: any) => messages.push(message), _runChatAgent: async ({ agentDelegationAuthority }: any) => { authorities.push(agentDelegationAuthority); }, _wrapRunAgentToNotify: (promise: Promise<void>) => promise };
		const selection = { type: 'Agent', label: 'Void application-level read-only', agentType: 'project-reader', catalogRevision: 'catalog-1', roleRevision: 'role-1', state: undefined } as const;
		fake._revokeAgentDelegation = revoke; fake._mcpService = { getMCPTools: () => [] };
		await (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse.call(fake, { userMessage: 'inspect', _chatSelections: [selection], threadId: 'parent' });
		assert.strictEqual(spawned, 0); assert.strictEqual(authorities.length, 1); assert.strictEqual(authorities[0].roles.revision, 'catalog-1'); assert.ok(messages[0].content.includes('spawn_agent with agent_type=project-reader exactly'));
		const routed = receiver(); const authority = Object.freeze({ allowed: true, generation: 0, roles: { revision: 'catalog-1', agents: [role], diagnostics: [] }, settingsState: {}, settingsOfProvider: {} });
		await runTool(routed.value, 'spawn_agent', 'named-spawn', { message: 'inspect', agent_type: 'project-reader' }, { authority: authority as Authority });
		assert.strictEqual(routed.calls[0][0], 'spawn'); assert.strictEqual(routed.calls[0][1][3], 'project-reader');
	});
	test('a stale named Agent role stops before history or provider send', async () => {
		let runs = 0, forgotten = 0; const streamState: any = {}, authority = Object.freeze({ allowed: true, generation: 7 }); const fake: any = { state: { allThreads: { parent: { messages: [], state: { stagingSelections: [] }, filesWithUserChanges: new Set<string>() } } }, streamState, _agentControlGeneration: new Map([['parent', 7]]), _agentDelegationAuthorityOfThread: new Map([['parent', authority]]), _agentSubagentService: { forgetParent() { forgotten++; }, cancelParent() { } }, _agentCustomAgentService: { getCatalog: async () => ({ revision: 'catalog-2', agents: [], diagnostics: [] }) }, _currentModelSelectionProps: () => ({ modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' }, modelSelectionOptions: {} }), _settingsService: { state: { globalSettings: { chatMode: 'agent' }, overridesOfModel: { openAI: { 'gpt-4.1': {} } } } }, _llmMessageService: { captureSettingsOfProvider: () => ({}) }, _beginInstructionTurn: async () => instructionSnapshot(), _purgeInstructionTurn() { }, _workspaceContextService: { getWorkspace: () => ({ folders: [{ uri: URI.parse('file:///workspace') }] }) }, _workspaceTrustManagementService: { isWorkspaceTrusted: () => true }, _agentSkillsService: { getCatalog: async () => createSkillCatalog([]), readSkillBody: async () => ({}) }, _directoryStringService: {}, _fileService: {}, _runChatAgent: () => { runs++; return Promise.resolve(); }, _setStreamState: (threadId: string, value: any) => streamState[threadId] = value };
		fake._revokeAgentDelegation = revoke;
		const result = await (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse.call(fake, { userMessage: 'inspect', _chatSelections: [{ type: 'Agent', label: 'Void application-level read-only', agentType: 'project-reader', catalogRevision: 'catalog-1', roleRevision: 'role-1', state: undefined }], threadId: 'parent' });
		assert.strictEqual(result, false); assert.strictEqual(runs, 0); assert.strictEqual(forgotten, 1); assert.strictEqual(fake._agentControlGeneration.get('parent'), 8); assert.strictEqual(fake._agentDelegationAuthorityOfThread.has('parent'), false); assert.strictEqual(fake.state.allThreads.parent.messages.length, 0); assert.ok(/changed or is no longer available/.test(streamState.parent.error.message));
	});
	test('a deferred custom-role catalog starts only after revocation and cannot admit a superseded turn', async () => {
		const messages: AdmissionMessage[] = [];
		const streamState: Record<string, AdmissionStream | undefined> = { parent: { isRunning: 'LLM', llmInfo: { displayContentSoFar: '', reasoningSoFar: '', toolCallSoFar: null }, interrupt: Promise.resolve(() => { }) } };
		const role: AdmissionRole = { identity: 'project-reader', revision: 'role-1', description: 'Project reader' };
		const catalog: AdmissionCatalog = { revision: 'catalog-1', agents: [role], diagnostics: [] };
		let catalogCalls = 0;
		let releaseFirstCatalog: (value: AdmissionCatalog) => void = () => { throw new Error('catalog was not entered'); };
		let catalogEntered: () => void = () => { throw new Error('catalog was not entered'); };
		const firstCatalogEntered = new Promise<void>(resolve => catalogEntered = resolve);
		const firstCatalog = new Promise<AdmissionCatalog>(resolve => releaseFirstCatalog = resolve);
		const fake = {
			state: { allThreads: { parent: { messages, state: { stagingSelections: [] }, filesWithUserChanges: new Set<string>() } } },
			streamState,
			_agentControlGeneration: new Map([['parent', 0]]),
			_parentRunTokenOfThread: new Map<string, symbol>(),
			_agentDelegationAuthorityOfThread: new Map(),
			_agentSubagentService: { cancelParent() { }, forgetParent() { } },
			_toolsService: { invalidateReadReceipts(_threadId: string) { } },
			_cancelChildToolApprovalsForParent(_threadId: string) { },
			_revokeAgentDelegation(threadId: string, forget = false) { admissionLifecycle._revokeAgentDelegation.call(this, threadId, forget); },
			async abortRunning(threadId: string) { this._revokeAgentDelegation(threadId); this._setStreamState(threadId, undefined); },
			_agentCustomAgentService: { getCatalog: async () => { catalogCalls++; if (catalogCalls === 1) { catalogEntered(); return firstCatalog; } return catalog; } },
			_currentModelSelectionProps: () => ({ modelSelection: { providerName: 'openAI', modelName: 'gpt-4.1' }, modelSelectionOptions: {} }),
			_settingsService: { state: { globalSettings: { chatMode: 'agent' }, overridesOfModel: { openAI: { 'gpt-4.1': {} } } } },
			_llmMessageService: { captureSettingsOfProvider: () => ({}) },
			_beginInstructionTurn: async () => instructionSnapshot(),
			_purgeInstructionTurn() { },
			_workspaceContextService: { getWorkspace: () => ({ folders: [{ uri: URI.parse('file:///workspace') }] }) },
			_workspaceTrustManagementService: { isWorkspaceTrusted: () => true },
			_agentSkillsService: { getCatalog: async () => createSkillCatalog([]), readSkillBody: async () => ({}) },
			_directoryStringService: {}, _fileService: {}, _mcpService: { getMCPTools: () => [] },
			_rememberInstructionTurn() { },
			_addMessageToThread(_threadId: string, message: AdmissionMessage) { messages.push(message); },
			_runChatAgent: async (_options: unknown) => { },
			_wrapRunAgentToNotify: (promise: Promise<void>) => promise,
			_setStreamState(threadId: string, value: AdmissionStream | undefined) { streamState[threadId] = value; },
		};
		const selection: AdmissionSelection = { type: 'Agent', label: 'Void application-level read-only', agentType: 'project-reader', catalogRevision: 'catalog-1', roleRevision: 'role-1', state: undefined };
		const first = admissionLifecycle._addUserMessageAndStreamResponse.call(fake, { userMessage: 'first', _chatSelections: [selection], threadId: 'parent' });
		await firstCatalogEntered;
		assert.strictEqual(fake._agentControlGeneration.get('parent'), 1); assert.strictEqual(streamState.parent, undefined); assert.strictEqual(messages.length, 0);
		await admissionLifecycle._addUserMessageAndStreamResponse.call(fake, { userMessage: 'second', _chatSelections: [selection], threadId: 'parent' });
		assert.strictEqual(fake._agentControlGeneration.get('parent'), 2); releaseFirstCatalog(catalog); assert.strictEqual(await first, false); assert.deepStrictEqual(messages.map(message => message.displayContent), ['second']);
	});
	test('mixed generic and named Agent selections are rejected before history or provider send in either order', async () => {
		for (const selections of [[{ type: 'Agent', label: 'Void application-level read-only', state: undefined }, { type: 'Agent', label: 'Void application-level read-only', agentType: 'project-reader', catalogRevision: 'catalog-1', roleRevision: 'role-1', state: undefined }], [{ type: 'Agent', label: 'Void application-level read-only', agentType: 'project-reader', catalogRevision: 'catalog-1', roleRevision: 'role-1', state: undefined }, { type: 'Agent', label: 'Void application-level read-only', state: undefined }]] as const) {
			let runs = 0; const fake: any = { state: { allThreads: { parent: { messages: [], state: { stagingSelections: [] } } } }, streamState: {}, _agentControlGeneration: new Map(), _agentDelegationAuthorityOfThread: new Map(), _agentSubagentService: { forgetParent() { } }, _runChatAgent: () => { runs++; return Promise.resolve(); } };
			await assert.rejects(() => (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse.call(fake, { userMessage: 'inspect', _chatSelections: selections, threadId: 'parent' }), /custom_agent_multiple_selections/);
			assert.strictEqual(runs, 0); assert.strictEqual(fake.state.allThreads.parent.messages.length, 0);
		}
	});
	test('an unsupported no-marker Agent route is diagnosed before any provider send', async () => {
		const streamState: any = {}; let runs = 0; const fake: any = { state: { allThreads: { parent: { state: { stagingSelections: [] } } }, globalSettings: { chatMode: 'agent' } }, streamState, _agentControlGeneration: new Map(), _agentDelegationAuthorityOfThread: new Map(), _agentSubagentService: { forgetParent() { } }, _currentModelSelectionProps: () => ({ modelSelection: { providerName: 'openAICompatible', modelName: 'custom-plain' }, modelSelectionOptions: {} }), _settingsService: { state: { globalSettings: { chatMode: 'agent' }, overridesOfModel: {} } }, _setStreamState: (threadId: string, value: any) => streamState[threadId] = value, _runChatAgent: () => { runs++; return Promise.resolve(); } };
		const result = await (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse.call(fake, { userMessage: 'delegate', _chatSelections: [], threadId: 'parent' });
		assert.strictEqual(result, false); assert.strictEqual(runs, 0); assert.ok(/does not support native Agent tools/.test(streamState.parent.error.message));
	});
	test('a no-model Agent route is diagnosed before any provider send', async () => {
		const streamState: any = {}; let runs = 0; const fake: any = { state: { allThreads: { parent: { state: { stagingSelections: [] } } }, globalSettings: { chatMode: 'agent' } }, streamState, _agentControlGeneration: new Map(), _agentDelegationAuthorityOfThread: new Map(), _agentSubagentService: { forgetParent() { } }, _currentModelSelectionProps: () => ({ modelSelection: null, modelSelectionOptions: undefined }), _settingsService: { state: { globalSettings: { chatMode: 'agent' }, overridesOfModel: {} } }, _setStreamState: (threadId: string, value: any) => streamState[threadId] = value, _runChatAgent: () => { runs++; return Promise.resolve(); } };
		const result = await (ChatThreadService.prototype as any)._addUserMessageAndStreamResponse.call(fake, { userMessage: 'delegate', _chatSelections: [], threadId: 'parent' });
		assert.strictEqual(result, false); assert.strictEqual(runs, 0); assert.ok(/selected Chat model/.test(streamState.parent.error.message));
	});
});
