import assert from 'assert';
import { CancellationTokenSource } from '../../../../../base/common/cancellation.js';
import { parse } from 'smol-toml';
import { AgentSkillCatalog, AgentRuntimeTurnSnapshot, SkillCandidate, beginSkillPickerQuery, closeSkillComposerDollarSession, createAgentRuntimeTurnSnapshot, createSkillCatalog, createSkillComposerDollarSession, explicitSkillSelectors, initialSkillPickerQueryState, isSkillComposerDollarQueryCharacter, replaceSkillComposerDollarSelection, replaceSkillComposerTrigger, resolveSkillSelector, reviveAgentRuntimeTurnSnapshot, selectExplicitSkills, settleSkillPickerQuery, skillAdvertisement, skillBodyRevision, skillComposerDollarEnterAction, skillComposerTriggerAtCursor, skillPickerDescriptors, strictSkillFromCandidate, updateSkillComposerDollarQuery } from '../../common/agentSkills.js';
import { parseAgentConfigSource, projectAgentConfig, resolveAgentInstructions, stableAgentInstructionRevision } from '../../common/agentInstructions.js';

const bytes = (text: string) => new TextEncoder().encode(text);
const candidate = (name = 'demo', source: SkillCandidate['source'] = 'repository', rank = 0, body = 'Body', pluginName?: string, metadata?: string): SkillCandidate => ({ source, rank, root: `file:///${source}`, skillRoot: `file:///${source}/${name}`, directoryName: name, bytes: bytes(`---\nname: ${name}\ndescription: ${name} description\n---\n${body}`), ...(pluginName ? { pluginName } : {}), ...(metadata === undefined ? {} : { openaiMetadata: bytes(metadata) }) });
const catalog = (...items: SkillCandidate[]) => createSkillCatalog(items);
const instructions = () => { const parsed = parseAgentConfigSource('user', 'file:///home/.codex/config.toml', { status: 'bytes', bytes: bytes('developer_instructions = "developer"') }, parse); const config = projectAgentConfig(parsed.projected, undefined, [parsed.provenance], 'file:///workspace', 'file:///workspace'); const sources = [{ uri: 'file:///workspace/AGENTS.md', outcome: Object.freeze({ status: 'bytes' as const, bytes: bytes('agents') }) }]; return resolveAgentInstructions(config, sources, stableAgentInstructionRevision(config, sources)); };
const model = { hasModel: true as const, providerName: 'provider', modelName: 'model', contextWindow: 10000, reservedOutputTokens: 10, modelSelectionOptions: { reasoningEnabled: true }, selectedModelOverrides: { temperature: 0.2, nested: { a: true } } };

suite('Agent Skills catalog and runtime', () => {
	test('keeps repository, user, bundled, and plugin provenance rank and identity', () => { const value = catalog(candidate('repo', 'repository', 0), candidate('user', 'user', 1), candidate('bundle', 'bundled', 2), candidate('plug', 'plugin', 3, 'Body', 'plugin')); assert.deepStrictEqual(value.skills.map(skill => [skill.identity, skill.provenance.source, skill.provenance.rank]), [['repo', 'repository', 0], ['user', 'user', 1], ['bundle', 'bundled', 2], ['plugin:plug', 'plugin', 3]]); });
	test('uses exact filename and body bytes for validation and revisions', () => { const valid = strictSkillFromCandidate(candidate('demo', 'repository', 0, 'first')); const changed = strictSkillFromCandidate(candidate('demo', 'repository', 0, 'second')); const mismatch = strictSkillFromCandidate({ ...candidate('demo'), directoryName: 'other' }); assert.ok(valid.skill); assert.notStrictEqual(valid.skill!.bodyRevision, changed.skill!.bodyRevision); assert.strictEqual(valid.skill!.bodyRevision, skillBodyRevision('---\nname: demo\ndescription: demo description\n---\nfirst')); assert.strictEqual(mismatch.skill, undefined); });
	test('isolates strict invalid UTF-8, frontmatter, YAML, names, and descriptions per item', () => { const invalid = [ { ...candidate(), bytes: new Uint8Array([0xff]) }, { ...candidate(), bytes: bytes('Body') }, { ...candidate(), bytes: bytes('---\nname: [\ndescription: x\n---') }, { ...candidate(), bytes: bytes('\uFEFF---\nname: demo\ndescription: demo\n---\nBody') }, candidate('a'.repeat(65)), { ...candidate(), directoryName: 'wrong' }, { ...candidate(), bytes: bytes('---\nname: demo\ndescription: " "\n---') }, { ...candidate(), bytes: bytes(`---\nname: demo\ndescription: ${'x'.repeat(1025)}\n---`) } ]; const value = catalog(candidate(), ...invalid); assert.deepStrictEqual(value.skills.map(skill => skill.identity), ['demo']); assert.deepStrictEqual(value.diagnostics.map(diagnostic => diagnostic.code), ['skill_invalid_utf8', 'skill_invalid_frontmatter', 'skill_invalid_frontmatter', 'skill_invalid_frontmatter', 'skill_invalid_name', 'skill_invalid_name', 'skill_invalid_description', 'skill_invalid_description']); });
	test('treats optional OpenAI metadata as absent, valid, omitted-policy, or fail-open diagnostic', () => { const absent = strictSkillFromCandidate(candidate()); const valid = strictSkillFromCandidate(candidate('valid', 'repository', 0, 'Body', undefined, 'policy:\n  allow_implicit_invocation: false')); const omitted = strictSkillFromCandidate(candidate('omit', 'repository', 0, 'Body', undefined, 'x: true')); const malformed = strictSkillFromCandidate(candidate('bad', 'repository', 0, 'Body', undefined, '[')); const utf8 = strictSkillFromCandidate({ ...candidate('utf8'), openaiMetadata: new Uint8Array([0xff]) }); const structure = strictSkillFromCandidate(candidate('structure', 'repository', 0, 'Body', undefined, '- item')); assert.deepStrictEqual([absent.skill!.implicit, valid.skill!.implicit, omitted.skill!.implicit], [true, false, true]); assert.deepStrictEqual([malformed, utf8, structure].map(value => value.diagnostics.length), [1, 1, 1]); });
	test('preserves loose duplicates while resolving unique bare and qualified names', () => { const value = catalog(candidate('same', 'repository', 0), candidate('same', 'plugin', 1, 'Body', 'plug'), candidate('only')); assert.strictEqual(value.skills.filter(skill => skill.name === 'same').length, 2); assert.strictEqual(resolveSkillSelector(value, 'only').skill!.identity, 'only'); assert.strictEqual(resolveSkillSelector(value, 'plug:same').skill!.identity, 'plug:same'); });
	test('reports bare and qualified ambiguity plus missing selectors', () => { const value = catalog(candidate('same'), candidate('same', 'repository', 1, 'Body', 'plug'), { ...candidate('same', 'repository', 2, 'Body', 'plug'), skillRoot: 'file:///other/same' }); assert.strictEqual(resolveSkillSelector(value, 'same').diagnostic!.code, 'skill_ambiguous'); assert.strictEqual(resolveSkillSelector(value, 'plug:same').diagnostic!.code, 'skill_ambiguous'); assert.strictEqual(resolveSkillSelector(value, 'missing').diagnostic!.code, 'skill_not_found'); });
	test('selects dollar tokens in first-seen order deterministically', () => { const value = catalog(candidate('one'), candidate('two')); assert.deepStrictEqual(explicitSkillSelectors('$two then $one then $two'), ['two', 'one']); assert.deepStrictEqual(selectExplicitSkills(value, '$two then $one').skills!.map(skill => skill.identity), ['two', 'one']); });
	test('keeps dollar literals in inline and fenced code while exposing only plain composer triggers', () => {
		const text = '$one `literal $two` and ``literal `$three``\n```ts\nconst x = "$four"\n```not-a-close\n$still-fenced\n``` \t\r\n   ~~~md\n$five\n   ~~~\n$plugin:six';
		assert.deepStrictEqual(explicitSkillSelectors(text), ['one', 'plugin:six']);
		assert.deepStrictEqual(skillComposerTriggerAtCursor('try $', 5), { index: 4, query: '' });
		assert.strictEqual(skillComposerTriggerAtCursor('`$literal`', 9), undefined);
		const fenced = '```\n$\n```'; assert.strictEqual(skillComposerTriggerAtCursor(fenced, fenced.indexOf('$') + 1), undefined);
	});
	test('does not open a Skills picker from an earlier selector while the newest dollar is code literal', () => {
		const inline = '$one `latest $`'; assert.strictEqual(skillComposerTriggerAtCursor(inline, inline.lastIndexOf('$') + 1), undefined);
		const fence = '````\n` $\n````'; assert.strictEqual(skillComposerTriggerAtCursor(fence, fence.indexOf('$') + 1), undefined);
	});
	test('replaces only the dollar trigger with canonical direct text and no selection side effect', () => {
		assert.deepStrictEqual(replaceSkillComposerTrigger('$', 0, 1, 'demo'), { text: '$demo', cursor: 5 });
		assert.deepStrictEqual(replaceSkillComposerTrigger('before $ after', 7, 8, 'plugin:demo'), { text: 'before $plugin:demo after', cursor: 19 });
		assert.deepStrictEqual(replaceSkillComposerTrigger('$demo and $', 10, 11, 'demo'), { text: '$demo and ', cursor: 10 });
		assert.strictEqual(replaceSkillComposerTrigger('$', 0, 1, 'bad identity'), undefined);
	});
	test('mirrors dollar query typing and deletion while close preserves and selection replaces the whole guarded token', async () => {
		assert.strictEqual(isSkillComposerDollarQueryCharacter('A'), true); assert.strictEqual(isSkillComposerDollarQueryCharacter(':'), true); assert.strictEqual(isSkillComposerDollarQueryCharacter('_'), true); assert.strictEqual(isSkillComposerDollarQueryCharacter(' '), false); assert.strictEqual(isSkillComposerDollarQueryCharacter('.'), false);
		let sentence = createSkillComposerDollarSession('Use $', 4)!; for (const query of ['d', 'de', 'demo']) sentence = updateSkillComposerDollarQuery(sentence, sentence.text, query)!;
		assert.strictEqual(updateSkillComposerDollarQuery(sentence, sentence.text, 'demo '), undefined); const delimiterClose = closeSkillComposerDollarSession(sentence, sentence.text)!; const nativeDelimiterText = `${delimiterClose.text} to inspect`; assert.strictEqual(nativeDelimiterText, 'Use $demo to inspect'); assert.deepStrictEqual(explicitSkillSelectors(nativeDelimiterText), ['demo']); assert.deepStrictEqual(explicitSkillSelectors('Use $demo. Then $plugin:other!'), ['demo', 'plugin:other']);
		let typing = createSkillComposerDollarSession('before $ after', 7)!;
		for (const query of ['p', 'pl', 'plug', 'plug:']) typing = updateSkillComposerDollarQuery(typing, typing.text, query)!;
		assert.strictEqual(typing.text, 'before $plug: after');
		typing = updateSkillComposerDollarQuery(typing, typing.text, 'plug')!; assert.strictEqual(typing.text, 'before $plug after');
		typing = updateSkillComposerDollarQuery(typing, typing.text, '')!; assert.strictEqual(typing.text, 'before $ after');

		const noResults = updateSkillComposerDollarQuery(createSkillComposerDollarSession('before $ after', 7)!, 'before $ after', 'missing')!;
		assert.strictEqual((await skillPickerDescriptors(async () => catalog(candidate('demo')))).some(item => item.identity === noResults.query), false);
		assert.strictEqual(closeSkillComposerDollarSession(noResults, noResults.text)!.text, 'before $missing after');
		const ambiguous = updateSkillComposerDollarQuery(createSkillComposerDollarSession('before $ after', 7)!, 'before $ after', 'same')!;
		const ambiguousOptions = await skillPickerDescriptors(async () => catalog(candidate('same'), candidate('same', 'plugin', 1, 'Body', 'plug'))); assert.strictEqual(ambiguousOptions.find(item => item.identity === ambiguous.query)?.kind, 'diagnostic');
		assert.strictEqual(closeSkillComposerDollarSession(ambiguous, ambiguous.text)!.text, 'before $same after');
		assert.strictEqual(updateSkillComposerDollarQuery(ambiguous, `${ambiguous.text}!`, 'changed'), undefined);

		const qualifiedQuery = updateSkillComposerDollarQuery(createSkillComposerDollarSession('before $ after', 7)!, 'before $ after', 'plug')!;
		assert.deepStrictEqual(replaceSkillComposerDollarSelection(qualifiedQuery, qualifiedQuery.text, 'plugin:demo'), { text: 'before $plugin:demo after', cursor: 19 });
		const duplicateQuery = updateSkillComposerDollarQuery(createSkillComposerDollarSession('$demo and $', 10)!, '$demo and $', 'de')!;
		assert.deepStrictEqual(replaceSkillComposerDollarSelection(duplicateQuery, duplicateQuery.text, 'demo'), { text: '$demo and ', cursor: 10 });
		assert.strictEqual(replaceSkillComposerDollarSelection(duplicateQuery, `${duplicateQuery.text} drift`, 'demo'), undefined);

		const stale = beginSkillPickerQuery(initialSkillPickerQueryState, 'demo'); assert.strictEqual(skillComposerDollarEnterAction(stale, 'demo', true), 'submit');
		const newer = beginSkillPickerQuery(stale, 'demo-two'); assert.strictEqual(settleSkillPickerQuery(newer, stale.revision, stale.query), undefined); assert.strictEqual(skillComposerDollarEnterAction(newer, 'demo-two', true), 'submit');
		const ready = settleSkillPickerQuery(newer, newer.revision, newer.query)!; assert.strictEqual(skillComposerDollarEnterAction(ready, ready.query, false), 'submit'); assert.strictEqual(skillComposerDollarEnterAction(ready, ready.query, true), 'select');
	});
	test('scans every bounded-message selector so a late missing identity fails visibly', () => { const values = Array.from({ length: 40 }, (_, index) => `$skill-${index}`); assert.strictEqual(explicitSkillSelectors(values.join(' ')).length, 40); assert.deepStrictEqual(explicitSkillSelectors(`$${'a'.repeat(65)} $valid`), ['valid']); const value = catalog(...values.slice(0, 33).map((_, index) => candidate(`skill-${index}`, 'repository', index))); const selected = selectExplicitSkills(value, `${values.slice(0, 33).join(' ')} $missing`); assert.strictEqual(selected.skills, undefined); assert.deepStrictEqual(selected.diagnostic, { code: 'skill_not_found', identity: 'missing' }); });
	test('loads empty, unique, duplicate, and cancelled late Skill picker descriptors canonically', async () => {
		assert.deepStrictEqual(await skillPickerDescriptors(async () => catalog()), []);
		const value = catalog(candidate('unique', 'repository', 0), candidate('same', 'repository', 1), candidate('same', 'plugin', 2, 'Body', 'plug'), candidate('qualified', 'plugin', 3, 'Body', 'plugdup'), { ...candidate('qualified', 'plugin', 4, 'Body', 'plugdup'), skillRoot: 'file:///other/qualified' });
		const descriptors = await skillPickerDescriptors(async () => value);
		assert.strictEqual(descriptors.length, 4); assert.deepStrictEqual(descriptors.map(item => [item.kind, item.identity]), [['diagnostic', 'same'], ['diagnostic', 'plugdup:qualified'], ['skill', 'unique'], ['skill', 'plug:same']]);
		const duplicate = descriptors[0]; assert.strictEqual(duplicate.kind === 'diagnostic' && duplicate.disabled, true); assert.strictEqual(duplicate.kind === 'diagnostic' && duplicate.label.length < 200, true); assert.strictEqual(descriptors.filter(item => item.identity === 'same').length, 1);
		assert.strictEqual(descriptors.find(item => item.identity === 'plug:same')?.kind, 'skill'); assert.strictEqual(descriptors.filter(item => item.identity === 'plugdup:qualified').length, 1); assert.strictEqual(descriptors.find(item => item.identity === 'plugdup:qualified')?.kind, 'diagnostic');
		let release!: (catalog: AgentSkillCatalog) => void; const deferred = new Promise<AgentSkillCatalog>(resolve => release = resolve); const source = new CancellationTokenSource(); const pending = skillPickerDescriptors(() => deferred, source.token); source.cancel(); release(value); assert.deepStrictEqual(await pending, []); source.dispose();
		const alreadyCancelled = new CancellationTokenSource(); alreadyCancelled.cancel(); let loads = 0; assert.deepStrictEqual(await skillPickerDescriptors(async () => { loads++; return value; }, alreadyCancelled.token), []); assert.strictEqual(loads, 0); alreadyCancelled.dispose();
	});
	test('fails explicit multi-selection atomically', () => { const value = catalog(candidate('one')); const selected = selectExplicitSkills(value, '$one $missing'); assert.strictEqual(selected.skills, undefined); assert.strictEqual(selected.diagnostic!.code, 'skill_not_found'); });
	test('advertises unknown context at exactly 8000 and known context at the 2 percent character floor', () => { const value = catalog(candidate('demo')); assert.strictEqual(skillAdvertisement(value, undefined).limit, 8000); assert.strictEqual(skillAdvertisement(value, 123).limit, Math.floor(123 * .02 * 4)); });
	test('shortens descriptions first, omits whole entries, and excludes implicit false from advertisement', () => { const firstDescription = 'x'.repeat(200); const first = strictSkillFromCandidate({ ...candidate('first'), bytes: bytes(`---\nname: first\ndescription: ${firstDescription}\n---`) }).skill!; const later = strictSkillFromCandidate({ ...candidate('later', 'repository', 1), bytes: bytes(`---\nname: later\ndescription: ${'y'.repeat(20)}\n---`) }).skill!; const hidden = strictSkillFromCandidate(candidate('hidden', 'repository', 2, 'Body', undefined, 'policy:\n  allow_implicit_invocation: false')).skill!; const rebuilt: AgentSkillCatalog = Object.freeze({ ...createSkillCatalog([candidate('base')]), skills: Object.freeze([first, later, hidden]) }); const ad = skillAdvertisement(rebuilt, 2000); const firstLine = ad.text.split('\n')[0]; assert.strictEqual(firstLine.includes('identity=first'), true); assert.strictEqual(firstLine.endsWith(firstDescription), false); assert.strictEqual(firstLine.includes('description=' + firstDescription.slice(0, 1)), true); assert.strictEqual(ad.text.includes('identity=later'), false); assert.strictEqual(ad.text.includes('identity=hidden'), false); assert.strictEqual(ad.omitted, 1); assert.strictEqual(ad.used, ad.text.length); assert.strictEqual(ad.limit, 160); assert.deepStrictEqual(ad.diagnostic, { code: 'skill_catalog_omitted', detail: `budget:${ad.used}/${ad.limit}; omitted:1` }); });
	test('keeps explicit selections full-body while advertisements contain no body bytes', () => { const value = catalog(candidate('demo', 'repository', 0, 'SECRET-BODY')); const ad = skillAdvertisement(value, undefined); const selected = selectExplicitSkills(value, '$demo'); assert.strictEqual(ad.text.includes('SECRET-BODY'), false); assert.strictEqual(selected.skills![0].bodyRevision, value.skills[0].bodyRevision); });
test('creates deeply frozen immutable runtime snapshots with body hash and model overrides', () => { const value = catalog(candidate('demo', 'repository', 0, 'SECRET-BODY')); const input = { ...model, selectedModelOverrides: { ...model.selectedModelOverrides, nested: { a: true } } }; const selected = [{ identity: 'demo', skillRoot: value.skills[0].provenance.skillRoot, bodyRevision: value.skills[0].bodyRevision, body: '---\nname: demo\ndescription: demo description\n---\nSECRET-BODY' }]; const snapshot = createAgentRuntimeTurnSnapshot(instructions(), value, skillAdvertisement(value, 1), selected, input, true); input.selectedModelOverrides.temperature = 1; (input.selectedModelOverrides.nested as any).a = false; selected[0].body = 'mutated'; assert.strictEqual(Object.isFrozen(snapshot), true); assert.strictEqual(Object.isFrozen(snapshot.selected), true); assert.strictEqual(Object.isFrozen(snapshot.selected[0]), true); assert.strictEqual(Object.isFrozen(snapshot.catalog.skills), true); assert.strictEqual(Object.isFrozen(snapshot.catalog.skills[0]), true); assert.strictEqual(Object.isFrozen(snapshot.catalog.skills[0].provenance), true); assert.strictEqual(Object.isFrozen(snapshot.instructions), true); assert.strictEqual(Object.isFrozen(snapshot.instructions.config), true); assert.strictEqual(Object.isFrozen(snapshot.instructions.config.configSources), true); assert.strictEqual(snapshot.workspaceTrustedAtAdmission, true); assert.strictEqual(snapshot.model.hasModel && snapshot.model.selectedModelOverrides.temperature, .2); assert.strictEqual(snapshot.model.hasModel && (snapshot.model.selectedModelOverrides.nested as any).a, true); assert.strictEqual(snapshot.selected[0].bodyRevision, skillBodyRevision(snapshot.selected[0].body)); });
test('revives valid runtime snapshots and preserves revision', () => { const value = catalog(candidate()); const body = '---\nname: demo\ndescription: demo description\n---\nBody'; const snapshot = createAgentRuntimeTurnSnapshot(instructions(), value, skillAdvertisement(value, 1), [{ identity: 'demo', skillRoot: value.skills[0].provenance.skillRoot, bodyRevision: value.skills[0].bodyRevision, body }], model, false); const revived = reviveAgentRuntimeTurnSnapshot(JSON.parse(JSON.stringify(snapshot))); assert.deepStrictEqual(revived, snapshot); assert.strictEqual(revived!.workspaceTrustedAtAdmission, false); assert.strictEqual(revived!.revision, snapshot.revision); });
test('fails closed for tampered legacy, malformed, and extra model-option snapshots', () => { const value = catalog(candidate()); const body = '---\nname: demo\ndescription: demo description\n---\nBody'; const selection = [{ identity: 'demo', skillRoot: value.skills[0].provenance.skillRoot, bodyRevision: value.skills[0].bodyRevision, body }]; const snapshot: AgentRuntimeTurnSnapshot = createAgentRuntimeTurnSnapshot(instructions(), value, skillAdvertisement(value, 1), selection, model, true); const mutate = (fn: (raw: any) => void) => { const raw = JSON.parse(JSON.stringify(snapshot)); fn(raw); return reviveAgentRuntimeTurnSnapshot(raw); }; assert.strictEqual(mutate(raw => raw.schemaVersion = 1), undefined); assert.strictEqual(reviveAgentRuntimeTurnSnapshot({}), undefined); assert.strictEqual(mutate(raw => delete raw.workspaceTrustedAtAdmission), undefined); assert.strictEqual(mutate(raw => raw.workspaceTrustedAtAdmission = false), undefined); assert.strictEqual(mutate(raw => raw.model.selectedModelOverrides.temperature = .9), undefined); assert.strictEqual(mutate(raw => raw.model.selectedModelOverrides.nested.a = false), undefined); assert.strictEqual(mutate(raw => raw.model.modelSelectionOptions.extra = true), undefined); assert.throws(() => createAgentRuntimeTurnSnapshot(instructions(), value, skillAdvertisement(value, 1), selection, { ...model, modelSelectionOptions: { ...model.modelSelectionOptions, extra: true } } as never, true), /skill_runtime_model_invalid/); });
});
