[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'
Set-StrictMode -Version Latest
Add-Type -AssemblyName System.IO.Compression
Add-Type -AssemblyName System.IO.Compression.FileSystem
. (Join-Path $PSScriptRoot 'release-content-manifest.ps1')

$Utf8NoBom = New-Object Text.UTF8Encoding($false, $true)
$Utf8Bom = New-Object Text.UTF8Encoding($true, $true)
$Results = New-Object Collections.ArrayList

function Write-FixtureText {
    param([string]$Path,[string]$Text,[switch]$Bom,[switch]$Empty)
    $parent=Split-Path -Parent $Path;if(-not(Test-Path -LiteralPath $parent)){New-Item -ItemType Directory -Path $parent -ErrorAction Stop|Out-Null}
    if($Empty){[IO.File]::WriteAllBytes($Path,[byte[]]@());return}
    if($Bom){$body=$Utf8Bom.GetBytes($Text);$preamble=$Utf8Bom.GetPreamble();$bytes=New-Object byte[] ($preamble.Length+$body.Length);[Array]::Copy($preamble,0,$bytes,0,$preamble.Length);[Array]::Copy($body,0,$bytes,$preamble.Length,$body.Length);[IO.File]::WriteAllBytes($Path,$bytes)}else{[IO.File]::WriteAllBytes($Path,$Utf8NoBom.GetBytes($Text))}
}

function Write-FixtureManifest {
    param($Case,$Manifest)
    Write-FixtureText $Case.ManifestPath ($Manifest|ConvertTo-Json -Depth 8)
}

function New-FixtureCase {
    param([string]$Root,[string]$Name)
    $caseRoot=Join-Path $Root $Name;$content=Join-Path $caseRoot 'release-content';New-Item -ItemType Directory -Path $content -ErrorAction Stop|Out-Null
    $outer=@'
# Outer

{{PORTABLE_SIZE}}
{{PORTABLE_SHA256}}
{{PORTABLE_ENTRIES}}
{{SOURCE_HEAD}}
{{BUILD_DATE_KST}}
'@
    Write-FixtureText (Join-Path $content 'README.md') $outer
    Write-FixtureText (Join-Path $content 'portable\README.md') "# Portable`n"
    Write-FixtureText (Join-Path $content 'portable\release-notes.md') "# {{PRODUCT_VERSION}}`n"
    Write-FixtureText (Join-Path $content 'shared\guide.md') "# Shared guide`n"
    $manifest=[ordered]@{schemaVersion=1;entries=@(
        [ordered]@{source='README.md';outerPath='README.md';materialization='outer-metadata'},
        [ordered]@{source='portable/README.md';portablePath='docs/README.md';materialization='copy'},
        [ordered]@{source='portable/release-notes.md';portablePath='docs/release-notes.md';materialization='product-version'},
        [ordered]@{source='shared/guide.md';outerPath='guides/guide.md';portablePath='docs/guides/guide.md';materialization='copy'}
    )}
    $case=[pscustomobject]@{Root=$caseRoot;ContentRoot=$content;ManifestPath=(Join-Path $content 'manifest.json');Manifest=$manifest}
    Write-FixtureManifest $case $manifest
    $case
}

function Add-Pass { param([string]$Name) [void]$Results.Add($Name) }
function Assert-Throws {
    param([string]$Name,[scriptblock]$Action)
    $threw=$false;try{& $Action}catch{$threw=$true};if(-not $threw){throw "Expected failure did not occur: $Name"};Add-Pass $Name
}

function Invoke-FixturePacker {
    param([string]$NodePath,[string]$PackerPath,[string]$ArtifactRoot,[string]$OutputPath,[string]$ManifestPath)
    $output=& $NodePath $PackerPath $ArtifactRoot $OutputPath $ManifestPath '9.9.9' 2>&1|Out-String
    if($LASTEXITCODE -ne 0){throw "Fixture package-portable.js failed ($LASTEXITCODE): $output"}
}

function Assert-ManifestRejectedByPowerShellAndJavaScript {
    param([string]$Name,$Case,[string]$NodePath,[string]$PackerPath,[string]$ArtifactRoot)
    Assert-Throws "$Name PowerShell" {Get-ReleaseContentManifest $Case.ManifestPath $Case.ContentRoot|Out-Null}
    $outputPath=Join-Path $Case.Root 'should-not-package.zip'
    $oldPreference=$ErrorActionPreference
    $exitCode=$null
    try {
        $ErrorActionPreference='Continue'
        $output=& $NodePath $PackerPath $ArtifactRoot $outputPath $Case.ManifestPath '9.9.9' 2>&1|Out-String
        $exitCode=$LASTEXITCODE
    } finally {
        $ErrorActionPreference=$oldPreference
    }
    if($exitCode -eq 0 -or (Test-Path -LiteralPath $outputPath)){throw "JavaScript packer accepted $Name. Output: $output"}
    Add-Pass "$Name JavaScript"
}

function New-DocsFixtureZip {
    param([string]$Path,$Manifest,[ValidateSet('legacy','exact','partial','extra','mismatch','empty','bom','path-mismatch')][string]$Mode)
    $plan=@(Get-ReleaseContentPlan $Manifest Portable -ProductVersion '9.9.9')
    $stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$zip=New-Object IO.Compression.ZipArchive($stream,[IO.Compression.ZipArchiveMode]::Create,$false)
    try {
        if($Mode -ne 'legacy'){
            $limit=if($Mode -ceq 'partial'){$plan.Count-1}else{$plan.Count}
            for($index=0;$index -lt $limit;$index++){$path=$plan[$index].Path;if($Mode -ceq 'path-mismatch' -and $index -eq 0){$path='docs/readme.md'};$entry=$zip.CreateEntry($path);$output=$entry.Open();try{$bytes=[byte[]]$plan[$index].Bytes;if($Mode -ceq 'mismatch' -and $plan[$index].Path -ceq 'docs/release-notes.md'){$bytes=[byte[]]$Utf8NoBom.GetBytes('# 9.8.8`n')};if($Mode -ceq 'empty' -and $index -eq 0){$bytes=[byte[]]@()};if($Mode -ceq 'bom' -and $index -eq 0){$text=$Utf8NoBom.GetString($bytes);$bytes=[byte[]]$Utf8Bom.GetPreamble()+[byte[]]$Utf8Bom.GetBytes($text)};$output.Write($bytes,0,$bytes.Length)}finally{$output.Dispose()}}
            if($Mode -ceq 'extra'){$entry=$zip.CreateEntry('docs/extra.md');$writer=New-Object IO.StreamWriter($entry.Open(),$Utf8NoBom);try{$writer.Write('extra')}finally{$writer.Dispose()}}
        }
    } finally {$zip.Dispose();$stream.Dispose()}
}

function Test-DocsFixtureZip {
    param([string]$Path,$Manifest,[int]$RequiredContract=-1,[ValidateSet('current','8ad348e')][string]$RequiredLayout,[switch]$HistoricalArchive)
    $zip=[IO.Compression.ZipFile]::OpenRead($Path);try{$by=@{};foreach($entry in $zip.Entries){if($by.ContainsKey($entry.FullName)){throw "duplicate $($entry.FullName)"};$by[$entry.FullName]=$entry};$arguments=@{EntriesByPath=$by;Manifest=$Manifest;ProductVersion='9.9.9';RequiredContract=$RequiredContract;HistoricalArchive=$HistoricalArchive};if(-not[string]::IsNullOrWhiteSpace($RequiredLayout)){$arguments.RequiredLayout=$RequiredLayout};Assert-ReleaseContentArchiveDocsContract @arguments}finally{$zip.Dispose()}
}

function Get-HistoricalFixtureBytes {
    param($Entry)
    [byte[]]$Utf8NoBom.GetBytes("# fixture $($Entry.Source)`n")
}

function New-HistoricalDocsFixtureZip {
    param([string]$Path,$Snapshot,[ValidateSet('exact','partial','extra','path','case','bom','utf8','empty')][string]$Mode='exact')
    $entries=@($Snapshot.PortableEntries);$limit=if($Mode -ceq 'partial'){$entries.Count-1}else{$entries.Count};$stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$zip=New-Object IO.Compression.ZipArchive($stream,[IO.Compression.ZipArchiveMode]::Create,$false)
    try{for($index=0;$index -lt $limit;$index++){$item=$entries[$index];$name=[string]$item.PortablePath;if($index -eq 0 -and $Mode -ceq 'path'){$name='docs/README/alias.md'}elseif($index -eq 0 -and $Mode -ceq 'case'){$name='docs/readme.md'};$bytes=[byte[]](Get-HistoricalFixtureBytes $item);if($index -eq 0 -and $Mode -ceq 'bom'){$bytes=[byte[]]$Utf8Bom.GetPreamble()+$bytes}elseif($index -eq 0 -and $Mode -ceq 'utf8'){$bytes=[byte[]]@(0xff)}elseif($index -eq 0 -and $Mode -ceq 'empty'){$bytes=[byte[]]@()};$entry=$zip.CreateEntry($name);$output=$entry.Open();try{$output.Write($bytes,0,$bytes.Length)}finally{$output.Dispose()}};if($Mode -ceq 'extra'){$entry=$zip.CreateEntry('docs/extra.md');$output=$entry.Open();try{$bytes=$Utf8NoBom.GetBytes('extra');$output.Write($bytes,0,$bytes.Length)}finally{$output.Dispose()}}}finally{$zip.Dispose();$stream.Dispose()}
}

function New-HistoricalOuterFixtureZip {
    param([string]$Path,[string]$PortablePath,$Portable,$Snapshot,[ValidateSet('exact','partial','extra','path','case','bom','utf8','shared-mismatch')][string]$Mode='exact')
    $root='Void-9.9.9-win32-x64-distribution';$docs=@($Snapshot.OuterEntries);$legacy='EXPLORATORY p50 24/24 @vscode/policy-watcher /chat/completions old_text: "" oneOf ERR_STREAM_PREMATURE_CLOSE';$content=@{};foreach($item in $docs){$content[$item.OuterPath]=if($item.OuterPath -ceq 'README.md'){[byte[]]$Utf8NoBom.GetBytes("# historical outer`n$legacy`n")}else{[byte[]](Get-HistoricalFixtureBytes $item)}};if($Mode -ceq 'shared-mismatch'){$shared=@($docs|Where-Object{$null -ne $_.PortablePath})[0];$content[$shared.OuterPath]=[byte[]]$Utf8NoBom.GetBytes("# mismatched shared`n")};$selected=if($Mode -ceq 'partial'){@($docs|Select-Object -SkipLast 1)}else{$docs};$innerLeaf=Split-Path -Leaf $PortablePath;$records=New-Object Collections.ArrayList;$stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$zip=New-Object IO.Compression.ZipArchive($stream,[IO.Compression.ZipArchiveMode]::Create,$false)
    try{for($index=0;$index -lt $selected.Count;$index++){$item=$selected[$index];$name=[string]$item.OuterPath;if($index -eq 0 -and $Mode -ceq 'path'){$name='readme/alias.md'}elseif($index -eq 0 -and $Mode -ceq 'case'){$name='readme.md'};$bytes=[byte[]]$content[$item.OuterPath];if($index -eq 0 -and $Mode -ceq 'bom'){$bytes=[byte[]]$Utf8Bom.GetPreamble()+$bytes}elseif($index -eq 0 -and $Mode -ceq 'utf8'){$bytes=[byte[]]@(0xff)};$entry=$zip.CreateEntry("$root/$name");$output=$entry.Open();try{$output.Write($bytes,0,$bytes.Length)}finally{$output.Dispose()};[void]$records.Add("$(Get-ReleaseContentBytesSha256 $bytes)  $name")};if($Mode -ceq 'extra'){$bytes=$Utf8NoBom.GetBytes('extra');$entry=$zip.CreateEntry("$root/extra.md");$output=$entry.Open();try{$output.Write($bytes,0,$bytes.Length)}finally{$output.Dispose()};[void]$records.Add("$(Get-ReleaseContentBytesSha256 $bytes)  extra.md")};$innerBytes=[IO.File]::ReadAllBytes($PortablePath);$entry=$zip.CreateEntry("$root/$innerLeaf",[IO.Compression.CompressionLevel]::NoCompression);$output=$entry.Open();try{$output.Write($innerBytes,0,$innerBytes.Length)}finally{$output.Dispose()};[void]$records.Add("$(Get-ReleaseContentBytesSha256 $innerBytes)  $innerLeaf");$sumBytes=$Utf8NoBom.GetBytes(($records -join "`n")+"`n");$entry=$zip.CreateEntry("$root/SHA256SUMS.txt");$output=$entry.Open();try{$output.Write($sumBytes,0,$sumBytes.Length)}finally{$output.Dispose()}}finally{$zip.Dispose();$stream.Dispose()}
}

function New-Contract0OuterFixtureZip {
    param([string]$Path,[string]$PortablePath)
    $root='Void-9.9.9-win32-x64-distribution';$innerLeaf=Split-Path -Leaf $PortablePath;$innerBytes=[IO.File]::ReadAllBytes($PortablePath);$record="$(Get-ReleaseContentBytesSha256 $innerBytes)  $innerLeaf`n";$stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$zip=New-Object IO.Compression.ZipArchive($stream,[IO.Compression.ZipArchiveMode]::Create,$false);try{$entry=$zip.CreateEntry("$root/$innerLeaf",[IO.Compression.CompressionLevel]::NoCompression);$output=$entry.Open();try{$output.Write($innerBytes,0,$innerBytes.Length)}finally{$output.Dispose()};$sum=$Utf8NoBom.GetBytes($record);$entry=$zip.CreateEntry("$root/SHA256SUMS.txt");$output=$entry.Open();try{$output.Write($sum,0,$sum.Length)}finally{$output.Dispose()}}finally{$zip.Dispose();$stream.Dispose()}
}

function New-CurrentOuterFixtureZip {
    param([string]$Path,[string]$PortablePath,$Manifest,[AllowNull()][string]$ReadmeOverride=$null)
    $root='Void-9.9.9-win32-x64-distribution';$innerLeaf=Split-Path -Leaf $PortablePath;$tokens=@{'{{PORTABLE_SIZE}}'='1 byte';'{{PORTABLE_SHA256}}'=('a'*64);'{{PORTABLE_ENTRIES}}'='1';'{{SOURCE_HEAD}}'=('b'*40);'{{BUILD_DATE_KST}}'='2026-08-06 KST'};$plan=@(Get-ReleaseContentPlan $Manifest Outer -OuterTokens $tokens);$records=New-Object Collections.ArrayList;$stream=[IO.File]::Open($Path,[IO.FileMode]::CreateNew,[IO.FileAccess]::Write,[IO.FileShare]::None);$zip=New-Object IO.Compression.ZipArchive($stream,[IO.Compression.ZipArchiveMode]::Create,$false);try{foreach($item in $plan){$bytes=if($PSBoundParameters.ContainsKey('ReadmeOverride') -and $item.Path -ceq 'README.md'){[byte[]]$Utf8NoBom.GetBytes($ReadmeOverride)}else{[byte[]]$item.Bytes};$entry=$zip.CreateEntry("$root/$($item.Path)");$output=$entry.Open();try{$output.Write($bytes,0,$bytes.Length)}finally{$output.Dispose()};[void]$records.Add("$(Get-ReleaseContentBytesSha256 $bytes)  $($item.Path)")};$innerBytes=[IO.File]::ReadAllBytes($PortablePath);$entry=$zip.CreateEntry("$root/$innerLeaf",[IO.Compression.CompressionLevel]::NoCompression);$output=$entry.Open();try{$output.Write($innerBytes,0,$innerBytes.Length)}finally{$output.Dispose()};[void]$records.Add("$(Get-ReleaseContentBytesSha256 $innerBytes)  $innerLeaf");$sum=$Utf8NoBom.GetBytes(($records -join "`n")+"`n");$entry=$zip.CreateEntry("$root/SHA256SUMS.txt");$output=$entry.Open();try{$output.Write($sum,0,$sum.Length)}finally{$output.Dispose()}}finally{$zip.Dispose();$stream.Dispose()}
}

$releaseScriptPath=Join-Path $PSScriptRoot 'release-win32-x64-portable.ps1';$releaseTokens=$null;$releaseErrors=$null;$releaseAst=[Management.Automation.Language.Parser]::ParseFile($releaseScriptPath,[ref]$releaseTokens,[ref]$releaseErrors);if($releaseErrors.Count -ne 0){throw "release script parser errors: $($releaseErrors.Message -join '; ')"};$releaseValidationFunctions=@('Read-Utf8NoBomText','Read-ZipEntryStrictUtf8NoBom','Get-Sha256Stream','Get-Sha256File','Get-NormalizedArchivePath','Assert-CanonicalArchiveEntryPath','Assert-NotReparsePoint','Assert-X64PeStream','Get-RuntimeManifest','Get-ProductVersionFromText','Assert-PortableArchive','Assert-OuterArchive');$definitions=@($releaseAst.FindAll({param($node)$node -is [Management.Automation.Language.FunctionDefinitionAst]},$true));$validationSource=foreach($name in $releaseValidationFunctions){$matches=@($definitions|Where-Object{$_.Name -ceq $name});if($matches.Count -ne 1){throw "Expected one release validator function named $name, got $($matches.Count)."};$matches[0].Extent.Text};. ([scriptblock]::Create(($validationSource -join "`n")))

function Test-HistoricalContract0PublishRouting {
    param([string]$Root,[string]$PackageScriptPath)
    $tokens=$null;$errors=$null;$ast=[Management.Automation.Language.Parser]::ParseFile($PackageScriptPath,[ref]$tokens,[ref]$errors);if($errors.Count -ne 0){throw "package parser errors: $($errors.Message -join '; ')"};$publish=@($ast.FindAll({param($node)$node -is [Management.Automation.Language.FunctionDefinitionAst] -and $node.Name -ceq 'Publish-PortableArchive'},$true));if($publish.Count -ne 1){throw 'Publish-PortableArchive function extraction failed.'};$source=$publish[0].Extent.Text
    & {param($FixtureRoot,$FunctionSource)$calls=New-Object Collections.ArrayList;. ([scriptblock]::Create($FunctionSource));function Assert-PortableArchive {param([string]$ArchivePath,[object[]]$PayloadEntries,$ContentManifest,[int]$RequiredContract,[string]$RequiredLayout,[string]$ArchiveMode);[void]$calls.Add([pscustomobject]@{Path=$ArchivePath;RequiredContract=$RequiredContract;HasLayout=$PSBoundParameters.ContainsKey('RequiredLayout');Layout=$RequiredLayout;Mode=$ArchiveMode});if($calls.Count -eq 3){throw 'synthetic published validation failure'};[pscustomobject]@{Entries=@();DocsContract=0;DocsLayout=$null;DocsCount=0;Docs=@()}};function Move-PackageFileWithBoundedRetry {param([string]$SourcePath,[string]$DestinationPath,[string]$Purpose)[IO.File]::Move($SourcePath,$DestinationPath)};function Remove-UnverifiedPublishedOutputForRollback {param([string]$CandidatePath)[IO.File]::Delete($CandidatePath)};function Remove-ExpectedPackageCleanupFile {param([string]$CandidatePath)[IO.File]::Delete($CandidatePath)};$temporary=Join-Path $FixtureRoot 'contract0-candidate.zip';$output=Join-Path $FixtureRoot 'contract0-final.zip';$backup=Join-Path $FixtureRoot '.contract0-final.zip.backup';[IO.File]::WriteAllBytes($temporary,[byte[]](1,2,3));[IO.File]::WriteAllBytes($output,[byte[]](9,8,7));$prior=(Get-FileHash $output -Algorithm SHA256).Hash;$failed=$false;$failureMessage=$null;try{Publish-PortableArchive -TemporaryPath $temporary -OutputPath $output -BackupPath $backup -OutputName 'contract0-final.zip' -PayloadEntries @([pscustomobject]@{}) -ContentManifest ([pscustomobject]@{}) -CandidateRequiredDocsContract 0 -CandidateArchiveMode Historical|Out-Null}catch{$failed=$true;$failureMessage=$_.Exception.Message};if(-not$failed -or $calls.Count -ne 4){throw "Historical contract0 rollback fixture did not exercise candidate/prior/published/restored validation: calls=$($calls.Count) failure=$failureMessage"};if(@($calls|Where-Object{$_.HasLayout -or $_.Mode -cne 'Historical'}).Count -ne 0){throw 'Historical contract0 publish/rollback validation received a docs layout or non-historical mode.'};if(-not(Test-Path $output -PathType Leaf) -or (Get-FileHash $output -Algorithm SHA256).Hash -cne $prior -or (Test-Path $backup)){throw 'Historical contract0 rollback did not restore the exact prior output.'};@($calls)} $Root $source
}

function Test-PreparedHistoricalPairPinning {
    param([string]$PackageScriptText)
    foreach($marker in @('$PreparedCandidate = Copy-AndValidatePreparedPortableArchive @preparedCopyArguments','$PreparedValidation = $PreparedCandidate.Validation','Prepared archive docs contract does not match the explicit requirement.','Prepared archive docs layout does not match the explicit requirement.','$CandidateRequiredDocsContract = if ($IsPreparedMode) { [int]$PreparedValidation.DocsContract } else { 1 }','$CandidateRequiredDocsLayout = if ($IsPreparedMode) { [string]$PreparedValidation.DocsLayout } else { ''current'' }')){if(-not$PackageScriptText.Contains($marker)){throw "Prepared historical pair pinning is missing: $marker"}}
    foreach($pair in @(@(0,$null),@(1,'current'),@(1,'8ad348e'))){$resolvedContract=[int]$pair[0];$resolvedLayout=[string]$pair[1];$PreparedValidation=[pscustomobject]@{DocsContract=$resolvedContract;DocsLayout=$resolvedLayout};$IsPreparedMode=$true;$CandidateRequiredDocsContract=if($IsPreparedMode){[int]$PreparedValidation.DocsContract}else{1};$CandidateRequiredDocsLayout=if($IsPreparedMode){[string]$PreparedValidation.DocsLayout}else{'current'};if($CandidateRequiredDocsContract -ne $resolvedContract -or $CandidateRequiredDocsLayout -cne $resolvedLayout){throw "Prepared historical resolved pair was not pinned: $resolvedContract/$resolvedLayout"};$substituteContract=if($resolvedContract -eq 0){1}else{0};$substituteLayout=if($resolvedLayout -ceq 'current'){'8ad348e'}else{'current'};$rejectContract=$substituteContract -ne $CandidateRequiredDocsContract;$rejectLayout=$CandidateRequiredDocsContract -eq 1 -and $substituteLayout -cne $CandidateRequiredDocsLayout;if(-not($rejectContract -or $rejectLayout)){throw "Prepared historical substitution was not rejected by the pinned pair: $resolvedContract/$resolvedLayout"}}
}

function Test-PreparedOwnedCopyAuthority {
    param([string]$Root,[string]$PackageScriptPath)
    $tokens=$null;$errors=$null;$ast=[Management.Automation.Language.Parser]::ParseFile($PackageScriptPath,[ref]$tokens,[ref]$errors);if($errors.Count -ne 0){throw "package parser errors: $($errors.Message -join '; ')"};$matches=@($ast.FindAll({param($node)$node -is [Management.Automation.Language.FunctionDefinitionAst] -and $node.Name -ceq 'Copy-AndValidatePreparedPortableArchive'},$true));if($matches.Count -ne 1){throw 'Prepared owned-copy function extraction failed.'};$source=$matches[0].Extent.Text;$copyMarker='[IO.File]::Copy($PreparedArchivePath, $TemporaryOutputPath, $false)';$validateMarker='$preparedArguments = @{ ArchivePath = $TemporaryOutputPath';$hashMarker='Get-FileHash -Algorithm SHA256 -LiteralPath $TemporaryOutputPath';$copyIndex=$source.IndexOf($copyMarker);$validateIndex=$source.IndexOf($validateMarker);$hashIndex=$source.IndexOf($hashMarker);if($copyIndex -lt 0 -or $validateIndex -le $copyIndex -or $hashIndex -le $validateIndex -or $source.Contains('ArchivePath = $PreparedArchivePath')){throw 'Prepared archive authority is not ordered copy-to-owned, validate-owned, hash-owned.'}
    & {param($FixtureRoot,$FunctionSource). ([scriptblock]::Create($FunctionSource));$external=$null;$owned=$null;$resolvedContract=-1;$resolvedLayout=$null;$calls=New-Object Collections.ArrayList;function Assert-PortableArchive {param([string]$ArchivePath,[object[]]$PayloadEntries,$ContentManifest,[int]$RequiredContract,[string]$RequiredLayout,[string]$ArchiveMode);if($ArchivePath -cne $owned -or $RequiredContract -ne -1 -or $PSBoundParameters.ContainsKey('RequiredLayout') -or $ArchiveMode -cne 'Historical'){throw 'Authoritative prepared validation did not receive the owned default-historical candidate.'};[void]$calls.Add($ArchivePath);[IO.File]::WriteAllBytes($external,[byte[]](99,98,97));[pscustomobject]@{Entries=@();DocsContract=$resolvedContract;DocsLayout=$resolvedLayout;DocsCount=0;Docs=@();Version='9.9.9'}};foreach($pair in @(@(0,$null),@(1,'current'),@(1,'8ad348e'))){$resolvedContract=[int]$pair[0];$resolvedLayout=[string]$pair[1];$external=Join-Path $FixtureRoot "prepared-source-$resolvedContract-$resolvedLayout.zip";$owned=Join-Path $FixtureRoot "prepared-owned-$resolvedContract-$resolvedLayout.zip";$original=[byte[]](1,2,3,$calls.Count);[IO.File]::WriteAllBytes($external,$original);$result=Copy-AndValidatePreparedPortableArchive -PreparedArchivePath $external -TemporaryOutputPath $owned -PayloadEntries @([pscustomobject]@{}) -ContentManifest ([pscustomobject]@{}) -RequiredDocsContract -1 -ArchiveMode Historical;if($result.Validation.DocsContract -ne $resolvedContract -or [string]$result.Validation.DocsLayout -cne $resolvedLayout -or -not(Test-ReleaseContentBytesEqual ([IO.File]::ReadAllBytes($owned)) $original) -or (Test-ReleaseContentBytesEqual ([IO.File]::ReadAllBytes($external)) $original)){throw "Prepared owned-copy authority failed for $resolvedContract/$resolvedLayout"};$ownedHash=(Get-FileHash -LiteralPath $owned -Algorithm SHA256).Hash.ToLowerInvariant();if($result.Length -ne $original.Length -or $result.Sha256 -cne $ownedHash){throw "Prepared owned-copy metadata mismatch for $resolvedContract/$resolvedLayout"}};if($calls.Count -ne 3){throw 'Prepared owned-copy validation call count mismatch.'}} $Root $source
}

$tempRoot=[IO.Path]::GetFullPath((Join-Path ([IO.Path]::GetTempPath()) ('void-release-content-test-'+[guid]::NewGuid().ToString('N'))))
$tempParent=[IO.Path]::GetFullPath([IO.Path]::GetTempPath()).TrimEnd([IO.Path]::DirectorySeparatorChar)+[IO.Path]::DirectorySeparatorChar
if(-not $tempRoot.StartsWith($tempParent,[StringComparison]::OrdinalIgnoreCase)){throw 'Fixture root escaped the system temporary directory.'}
New-Item -ItemType Directory -Path $tempRoot -ErrorAction Stop|Out-Null

try {
    $production=Get-ReleaseContentManifest -ManifestPath (Join-Path $PSScriptRoot 'release-content\manifest.json') -ContentRoot (Join-Path $PSScriptRoot 'release-content')
    $ReleaseContentManifest=$production
    $currentTuples=@($production.Entries|ForEach-Object{"$($_.Source)|$($_.OuterPath)|$($_.PortablePath)|$($_.Materialization)"});$expectedCurrentTuples=@('README.md|README.md||outer-metadata','portable/README.md||docs/README.md|copy','portable/getting-started.md||docs/getting-started.md|copy','portable/release-notes.md||docs/release-notes.md|product-version','guides/write-tool-guide.md|guides/write-tool-guide.md|docs/guides/write-tool-guide.md|copy','guides/read-tool-guide.md|guides/read-tool-guide.md|docs/guides/read-tool-guide.md|copy','guides/agent-instructions-guide.md|guides/agent-instructions-guide.md|docs/guides/agent-instructions-guide.md|copy','prompts/write-tool-test-prompts.md|prompts/write-tool-test-prompts.md|docs/prompts/write-tool-test-prompts.md|copy','prompts/read-tool-test-prompts.md|prompts/read-tool-test-prompts.md|docs/prompts/read-tool-test-prompts.md|copy','prompts/agent-instructions-test-prompts.md|prompts/agent-instructions-test-prompts.md|docs/prompts/agent-instructions-test-prompts.md|copy','guides/ghost-chat-guide.md|guides/ghost-chat-guide.md|docs/guides/ghost-chat-guide.md|copy','prompts/ghost-chat-test-prompts.md|prompts/ghost-chat-test-prompts.md|docs/prompts/ghost-chat-test-prompts.md|copy');$currentShared=@($production.Entries|Where-Object{$null -ne $_.OuterPath -and $null -ne $_.PortablePath});if(($currentTuples -join "`n") -cne ($expectedCurrentTuples -join "`n") -or $production.Entries.Count -ne 12 -or $production.PortableEntries.Count -ne 11 -or $production.OuterEntries.Count -ne 9 -or $currentShared.Count -ne 8){throw 'Production release content manifest does not have the exact approved 12 tuples / 11 portable / 9 outer / 8 shared mapping.'};Add-Pass 'production exact 12 tuples and 11 portable 9 outer 8 shared'
    $productionRoot=[IO.Path]::GetFullPath((Join-Path $PSScriptRoot 'release-content'));$productionPhysical=@(Get-ChildItem -LiteralPath $productionRoot -File -Recurse -Force|ForEach-Object{$_.FullName.Substring($productionRoot.TrimEnd([IO.Path]::DirectorySeparatorChar).Length).TrimStart([IO.Path]::DirectorySeparatorChar,[IO.Path]::AltDirectorySeparatorChar).Replace([char]92,[char]47)});$expectedPhysical=@('manifest.json')+@($production.Entries|ForEach-Object{$_.Source});if($productionPhysical.Count -ne 13 -or @($expectedPhysical|Where-Object{$productionPhysical -cnotcontains $_}).Count -ne 0 -or @($productionPhysical|Where-Object{$expectedPhysical -cnotcontains $_}).Count -ne 0){throw 'Production release content physical tree must be exactly 12 manifest sources plus manifest.json.'};Add-Pass 'production physical 13 files including manifest'
    $portableForbiddenText='([A-Z]:\\|\bapi[ _-]?key\b|\bcustom headers?\b|\b(?:task|thread)[ _-]?ids?\b|\bcorporate host\b|\uC0AC\uB0B4|\bspec[\\/])';foreach($entry in $production.PortableEntries){if([regex]::IsMatch([string]$entry.SourceText,$portableForbiddenText,[Text.RegularExpressions.RegexOptions]::IgnoreCase)){throw "Production portable source contains forbidden internal or sensitive text: $($entry.Source)"}};Add-Pass 'production portable sources exclude forbidden internal and sensitive text'
    $historicalSnapshot=Get-ReleaseContent8ad348eContractSnapshot;$oldTuples=@($historicalSnapshot.Entries|ForEach-Object{"$($_.Source)|$($_.OuterPath)|$($_.PortablePath)|$($_.Materialization)"});$expectedOldTuples=$expectedCurrentTuples[0..5]+$expectedCurrentTuples[7..8];$oldShared=@($historicalSnapshot.Entries|Where-Object{$null -ne $_.OuterPath -and $null -ne $_.PortablePath});if($historicalSnapshot.Layout -cne '8ad348e' -or ($oldTuples -join "`n") -cne ($expectedOldTuples -join "`n") -or $historicalSnapshot.PortableEntries.Count -ne 7 -or $historicalSnapshot.OuterEntries.Count -ne 5 -or $oldShared.Count -ne 4){throw '8ad348e snapshot does not have the exact old 8 tuples / 7 portable / 5 outer / 4 shared mapping.'};Add-Pass '8ad348e exact snapshot and 7 portable 5 outer 4 shared'
    $productionTokens=@{'{{PORTABLE_SIZE}}'='1 byte';'{{PORTABLE_SHA256}}'=('a'*64);'{{PORTABLE_ENTRIES}}'='1';'{{SOURCE_HEAD}}'=('b'*40);'{{BUILD_DATE_KST}}'='2026-08-06 KST'}
    $productionPlans=@(Get-ReleaseContentPlan $production Portable -ProductVersion '9.9.9')+@(Get-ReleaseContentPlan $production Outer -OuterTokens $productionTokens)
    $productionUserText=(@($productionPlans|ForEach-Object{$Utf8NoBom.GetString([byte[]]$_.Bytes)})) -join "`n"
    $datedInternalRoute='(?i)(?<![a-z0-9])gpt-[a-z0-9._-]*\d{4}-\d{2}-\d{2}(?![a-z0-9])'
    if($productionUserText.Contains('gpt-5.6-luna-2026-07-09') -or $productionUserText -match $datedInternalRoute){throw 'Production user documentation contains a dated internal model route.'};Add-Pass 'production user docs exclude dated internal routes'
    if($productionUserText.Contains('750ms')){throw 'Production current user documentation retains the obsolete Ghost debounce instruction.'}
    $staleUniversalAgentClaims=@('4 accepted','2 running','Child depth는 1','depth-1','nesting은 허용하지 않습니다','no nesting','bounded read-only','read-only child 범위');foreach($claim in $staleUniversalAgentClaims){if($productionUserText.Contains($claim)){throw "Production current user documentation retains a stale universal Agent claim: $claim"}};$staleUnqualifiedRestartClaim='Chat별 unsent draft는 이동 뒤 복원되지만 restart에는 persist하지 않습니다.';if($productionUserText.Contains($staleUnqualifiedRestartClaim)){throw 'Production current user documentation retains the old unqualified restart statement.'}
    $exactReadOnlyCopy=[string]::Concat('Void application-level read-only ',[char]0x2014,' terminal disabled, no OS sandbox')
    $currentUserAnchors=@('AGENTS.md','.agents/skills','.codex/agents','@Agent','max_accepted_children','max_concurrent_threads_per_session','max_depth','1..8','default `4`','default `2`','default `1`','FIFO','wait_agent','interrupt_agent','read_only','inherit_parent_write','frozen parent tool snapshot','manual approval','Undo','one mutation-capable child','shared nested group budget','$qualified:identity','Markdown code','missing/ambiguous','Read Skill resource','Start child Agent','Wait for child Agent','Interrupt child Agent','MCP fallback','(empty message)','reasoning-only','View Past Chats','not rendered below the current Chat composer','native checkbox','forced-colors','Windows OS High Contrast','128 events','Usage unavailable',$exactReadOnlyCopy,'search_pathnames_only','search_for_files','bundled Search backend','automatic controlled fallback','system ripgrep','search_backend_unavailable','search_in_file','saved-disk','terminal capability','extra approval','packaged release smoke','Ghost Chat','Enable Ghost Chat code suggestions','Show suggestions on select','production automatic suggestions are unavailable','gpt-5.6-luna','unsent composer draft','memory-only','32 records / UTF-8 64 KiB','dormant','auto-send','Resume','bounded expandable Child activity card','full child transcript/session','cumulative-send quota','logical in-flight provider-dispatch lease','Provider-native multi-tool batch','ordinal identity','provider order','multi_tool_use.parallel','exact safe read','serialized/exclusive','Plan/orchestration','same-child follow-up','packaged process-restart E2E')
    $duplicateCurrentUserAnchors=@($currentUserAnchors|Group-Object|Where-Object{$_.Count -ne 1});if($duplicateCurrentUserAnchors.Count -ne 0){throw "Production current user documentation anchor list contains duplicates: $($duplicateCurrentUserAnchors.Name -join ', ')"};foreach($anchor in $currentUserAnchors){if(-not $productionUserText.Contains($anchor)){throw "Production current user documentation anchor is missing: $anchor"}}
    $perSourceCurrentAnchors=[ordered]@{
        'README.md'=@('max_accepted_children','max_concurrent_threads_per_session','max_depth','read_only','inherit_parent_write','frozen parent tool snapshot','manual approval','shared nested group budget','$qualified:identity','missing/ambiguous','MCP fallback','(empty message)','not rendered below the current Chat composer','native checkbox','Windows OS High Contrast','memory-only','32 records / UTF-8 64 KiB','bounded expandable Child activity card','multi_tool_use.parallel','exact safe read','same-child follow-up')
        'guides/agent-instructions-guide.md'=@('max_accepted_children','max_concurrent_threads_per_session','max_depth','read_only','inherit_parent_write','frozen parent tool snapshot','manual approval','one mutation-capable child','shared nested group budget','$qualified:identity','Markdown code','Read Skill resource','Start child Agent','Wait for child Agent','Interrupt child Agent','(empty message)','View Past Chats','not rendered below the current Chat composer','memory-only','32 records / UTF-8 64 KiB','dormant','Resume','Provider-native multi-tool batch','ordinal identity','serialized/exclusive','same-child follow-up')
        'portable/getting-started.md'=@('max_accepted_children','max_concurrent_threads_per_session','max_depth','read_only','inherit_parent_write','manual approval','shared nested group budget','native checkbox','forced-colors','Windows OS High Contrast')
        'portable/release-notes.md'=@('max_accepted_children','max_concurrent_threads_per_session','max_depth','read_only','inherit_parent_write','frozen parent tool snapshot','manual approval','Read Skill resource','Start child Agent','Wait for child Agent','Interrupt child Agent','(empty message)','View Past Chats','not rendered below the current Chat composer','native checkbox','forced-colors','Windows OS High Contrast','unsent composer draft','32 records / UTF-8 64 KiB','dormant','Resume','bounded expandable Child activity card','cumulative-send quota','logical in-flight provider-dispatch lease','Provider-native multi-tool batch','multi_tool_use.parallel','exact safe read','Plan/orchestration','packaged process-restart E2E')
    }
    foreach($source in $perSourceCurrentAnchors.Keys){$entry=@($production.Entries|Where-Object{$_.Source -ceq $source});if($entry.Count -ne 1){throw "Production current user documentation source is missing or duplicated: $source"};$sourceText=[string]$entry[0].SourceText;foreach($claim in $staleUniversalAgentClaims){if($sourceText.Contains($claim)){throw "Production current user documentation source retains a stale universal Agent claim: $source / $claim"}};if($sourceText.Contains($staleUnqualifiedRestartClaim)){throw "Production current user documentation source retains the old unqualified restart statement: $source"};$anchors=@($perSourceCurrentAnchors[$source]);if(@($anchors|Group-Object|Where-Object{$_.Count -ne 1}).Count -ne 0){throw "Production per-source anchor list contains duplicates: $source"};foreach($anchor in $anchors){if(-not $sourceText.Contains($anchor)){throw "Production current user documentation source anchor is missing: $source / $anchor"}}}
    Add-Pass 'production current Agent Skills Chat Settings Search and suggestion user docs anchors'
    $packageScriptPath=Join-Path $PSScriptRoot 'package-portable.ps1';$packageTokens=$null;$packageParseErrors=$null;$null=[System.Management.Automation.Language.Parser]::ParseFile($packageScriptPath,[ref]$packageTokens,[ref]$packageParseErrors);if($packageParseErrors.Count -ne 0){throw "package-portable parser errors: $($packageParseErrors.Message -join '; ')"};$packageScriptText=[IO.File]::ReadAllText($packageScriptPath);if($packageScriptText.Contains('$PSDefaultParameterValues')){throw 'package-portable must not use script-global archive validation defaults.'};if(@([regex]::Matches($packageScriptText,'Assert-PortableArchive (?:-|@)')).Count -ne 6){throw 'package-portable must retain exactly six archive validation call sites.'};foreach($marker in @("[ValidateSet('current', '8ad348e')][string]`$RequiredDocsLayout","[ValidateSet('current', '8ad348e')][string]`$RequiredLayout","[ValidateSet('Current', 'Historical')][string]`$ArchiveMode = 'Current'","`$candidateValidationArguments.RequiredLayout = `$CandidateRequiredDocsLayout","`$publishedValidationArguments.RequiredLayout = `$CandidateRequiredDocsLayout","`$restoreArguments.RequiredLayout = [string]`$previousDocsLayout","`$preparedArguments.RequiredLayout = `$RequiredDocsLayout","Historical contract 1 prepared archives require an explicit docs layout.","`$publishArguments.CandidateRequiredDocsLayout = `$CandidateRequiredDocsLayout")){if(-not $packageScriptText.Contains($marker)){throw "package-portable layout routing is missing: $marker"}};Add-Pass 'portable archive mode and explicit layout routing';Test-PreparedHistoricalPairPinning $packageScriptText;Add-Pass 'prepared historical default pins contract0 current and 8ad348e pairs';Test-PreparedOwnedCopyAuthority $tempRoot $packageScriptPath;Add-Pass 'prepared external substitution cannot change owned authoritative candidate';$contract0Calls=@(Test-HistoricalContract0PublishRouting $tempRoot $packageScriptPath);if($contract0Calls.Count -ne 4){throw 'Historical contract0 publish routing call count mismatch.'};Add-Pass 'historical contract0 candidate published rollback keeps layout absent'
    $releaseScriptText=[IO.File]::ReadAllText($releaseScriptPath);foreach($marker in @("[ValidateSet('current','8ad348e')][string]`$RequiredDocsLayout",'DocsLayout=$docs.Layout','Get-ReleaseContent8ad348eContractSnapshot','Current outer validation requires the current docs layout','Expected inner and outer docs layouts do not match.',"'-RequiredDocsLayout',`$requiredDocsLayout",'Assert-PortableArchive $portableFiles[0].FullName -HistoricalArchive','Assert-OuterArchive $outerFiles[0].FullName $portable -HistoricalArchive','Assert-OuterArchive $outerCopy $portable -HistoricalArchive','Assert-OuterArchive $outerPath $portable -HistoricalArchive','Assert-CanonicalPackageFiles $context.oldValidated.portable $context.oldValidated.outer $context.stage -HistoricalArchive','Assert-PortableArchive $candidatePath -RequiredDocsContract 1','docsLayout=$portable.DocsLayout','docsLayout=$outer.DocsLayout','docsLayout=$recoveryCopies.portable.DocsLayout','docsLayout=$recoveryCopies.outer.DocsLayout','docsLayout=$final.portable.DocsLayout','docsLayout=$final.outer.DocsLayout')){if(-not $releaseScriptText.Contains($marker)){throw "Historical/strict archive layout routing is missing: $marker"}};Add-Pass 'historical preflight strict layout routing and summary projections'
    foreach($marker in @('function Invoke-ControlledSearchBackendSmoke','smoke-search-bundled-version','smoke-search-bundled-pathname','smoke-search-bundled-content','smoke-search-controlled-fallback-pathname','smoke-search-controlled-fallback-content','smoke-search-both-unavailable','[IO.File]::Copy($bundled,$fallbackRipgrep,$false)','$env:PATH=$fallbackBin+[IO.Path]::PathSeparator+$oldPath','Invoke-ExactMoveWithRetry $bundled $backup $bundledParent','Invoke-ExactMoveWithRetry $backup $bundled $bundledParent','Remove-ExactPathWithRetry $fallbackBin $SmokeRoot','Bundled ripgrep restore hash mismatch.','$smoke.searchBackend=Invoke-ControlledSearchBackendSmoke','terminal-fallback-unavailable','commandLeakage=0')){if(-not $releaseScriptText.Contains($marker)){throw "Controlled Search extracted-candidate smoke is missing: $marker"}};Add-Pass 'controlled Search extracted candidate primary hermetic fallback unavailable and restore smoke'
    $contextStart=$releaseScriptText.IndexOf('function New-CanonicalReleaseContext');$contextEnd=$releaseScriptText.IndexOf('function Assert-SourceRuntimePayloads',$contextStart);if($contextStart -lt 0 -or $contextEnd -le $contextStart){throw 'Canonical release context function boundaries are missing.'};$contextText=$releaseScriptText.Substring($contextStart,$contextEnd-$contextStart);if(-not $contextText.Contains("recovery=`$dirs['recovery']")){throw 'Canonical release context does not return its recovery directory.'};foreach($consumer in @('$recovery=Assert-ImmediateChild $Context.stage $Context.recovery','$recoveryRoot=Assert-ImmediateChild $Context.stage $Context.recovery','-PreservedRoot $Context.recovery')){if(-not $releaseScriptText.Contains($consumer)){throw "Canonical recovery context consumer is missing: $consumer"}};Add-Pass 'canonical context returns recovery to consumers'
    $prepublicationCatch=$releaseScriptText.Substring($releaseScriptText.LastIndexOf('$verificationErrors=New-Object Collections.ArrayList'));if($prepublicationCatch.Contains('Publish-ReleaseSummaryTransaction')){throw 'Prepublication failure must not publish the canonical release summary.'};if(-not $prepublicationCatch.Contains('Assert-ExistingReleaseSummaryStateUnchanged $context.oldSummary $context.oldValidated')){throw 'Prepublication failure must verify the canonical release summary snapshot.'};if(@([regex]::Matches($releaseScriptText,'Publish-ReleaseSummaryTransaction \$context\.summary \$finalSummaryPath')).Count -lt 3){throw 'Postpublication canonical summary publication routing is missing.'};Add-Pass 'prepublication summary stays absent or byte-exact'

    $positive=New-FixtureCase $tempRoot 'positive';$positiveManifest=Get-ReleaseContentManifest $positive.ManifestPath $positive.ContentRoot
    if($positiveManifest.PortableEntries.Count -ne 3 -or $positiveManifest.OuterEntries.Count -ne 2){throw 'Positive fixture mapping count mismatch.'};Add-Pass 'positive manifest'

    $escape=New-FixtureCase $tempRoot 'escape';$escape.Manifest.entries[1].source='../outside.md';Write-FixtureManifest $escape $escape.Manifest;Assert-Throws 'source escape' {Get-ReleaseContentManifest $escape.ManifestPath $escape.ContentRoot|Out-Null}

    $duplicate=New-FixtureCase $tempRoot 'duplicate';Write-FixtureText (Join-Path $duplicate.ContentRoot 'portable\other.md') "other`n";$duplicate.Manifest.entries+=,[ordered]@{source='portable/other.md';portablePath='docs/readme.md';materialization='copy'};Write-FixtureManifest $duplicate $duplicate.Manifest;Assert-Throws 'portable case collision' {Get-ReleaseContentManifest $duplicate.ManifestPath $duplicate.ContentRoot|Out-Null}

    $missing=New-FixtureCase $tempRoot 'missing';[IO.File]::Delete((Join-Path $missing.ContentRoot 'shared\guide.md'));Assert-Throws 'missing source' {Get-ReleaseContentManifest $missing.ManifestPath $missing.ContentRoot|Out-Null}

    $empty=New-FixtureCase $tempRoot 'empty';Write-FixtureText (Join-Path $empty.ContentRoot 'shared\guide.md') '' -Empty;Assert-Throws 'empty source' {Get-ReleaseContentManifest $empty.ManifestPath $empty.ContentRoot|Out-Null}

    $bom=New-FixtureCase $tempRoot 'bom';Write-FixtureText (Join-Path $bom.ContentRoot 'shared\guide.md') "guide`n" -Bom;Assert-Throws 'BOM source' {Get-ReleaseContentManifest $bom.ManifestPath $bom.ContentRoot|Out-Null}

    $placeholder=New-FixtureCase $tempRoot 'placeholder';Write-FixtureText (Join-Path $placeholder.ContentRoot 'shared\guide.md') "{{UNRESOLVED}}`n";Assert-Throws 'unresolved placeholder' {Get-ReleaseContentManifest $placeholder.ManifestPath $placeholder.ContentRoot|Out-Null}

    $materialization=New-FixtureCase $tempRoot 'materialization';$materialization.Manifest.entries[3].materialization='future-mode';Write-FixtureManifest $materialization $materialization.Manifest;Assert-Throws 'unsupported materialization' {Get-ReleaseContentManifest $materialization.ManifestPath $materialization.ContentRoot|Out-Null}

    $legacyZip=Join-Path $positive.Root 'Void-9.9.9-win32-x64-portable.zip';New-DocsFixtureZip $legacyZip $positiveManifest legacy;$legacy=Test-DocsFixtureZip $legacyZip $positiveManifest -HistoricalArchive;if($legacy.Contract -ne 0 -or $null -ne $legacy.Layout){throw 'Historical legacy fixture did not report docs contract 0 without a layout.'};Add-Pass 'historical contract 0 accepted';Assert-Throws 'current rejects legacy contract 0' {Test-DocsFixtureZip $legacyZip $positiveManifest|Out-Null};Assert-Throws 'candidate rejects legacy 0' {Test-DocsFixtureZip $legacyZip $positiveManifest 1|Out-Null};$legacyPortableMeta=[pscustomobject]@{Path=$legacyZip;Size=(Get-Item $legacyZip).Length;Sha256=(Get-FileHash $legacyZip -Algorithm SHA256).Hash.ToLowerInvariant();Version='9.9.9';DocsContract=0;DocsLayout=$null;DocsCount=0;Docs=@()};$legacyOuterPath=Join-Path $positive.Root 'Void-9.9.9-win32-x64-distribution-bundle.zip';New-Contract0OuterFixtureZip $legacyOuterPath $legacyZip;$legacyOuter=Assert-OuterArchive $legacyOuterPath $legacyPortableMeta -HistoricalArchive;$legacyOuterSelf=Assert-OuterArchive $legacyOuterPath -HistoricalArchive;if($null -ne $legacyOuter.DocsLayout -or $null -ne $legacyOuterSelf.DocsLayout -or $legacyOuter.Entries -ne 2 -or $legacyOuter.OuterDocsCount -ne 0 -or $legacyOuter.ChecksumRecordCount -ne 1 -or $legacyOuter.SharedDocsCount -ne 0){throw 'Historical contract0 outer did not report physical2/outer-docs0/checksum1/shared0/no-layout.'};Add-Pass 'historical contract0 portable outer and null-expected self-check';Assert-Throws 'current rejects contract0 outer' {Assert-OuterArchive $legacyOuterPath $legacyPortableMeta|Out-Null}

    $exactZip=Join-Path $positive.Root 'exact.zip';New-DocsFixtureZip $exactZip $positiveManifest exact;$exact=Test-DocsFixtureZip $exactZip $positiveManifest 1 current;if($exact.Contract -ne 1 -or $exact.Layout -cne 'current' -or $exact.Count -ne 3){throw 'Exact current fixture did not report contract 1/current.'};$exactHistorical=Test-DocsFixtureZip $exactZip $positiveManifest 1 current -HistoricalArchive;if($exactHistorical.Layout -cne 'current'){throw 'Historical mode did not accept the exact current layout.'};Add-Pass 'current exact layout passes current and historical modes'

    $currentRoot=Join-Path $tempRoot 'current-layout';New-Item -ItemType Directory -Path $currentRoot|Out-Null;$currentPortablePath=Join-Path $currentRoot 'Void-9.9.9-win32-x64-portable.zip';New-DocsFixtureZip $currentPortablePath $production exact;$currentDocs=Test-DocsFixtureZip $currentPortablePath $production 1 current;$currentPortableMeta=[pscustomobject]@{Path=$currentPortablePath;Size=(Get-Item $currentPortablePath).Length;Sha256=(Get-FileHash $currentPortablePath -Algorithm SHA256).Hash.ToLowerInvariant();Version='9.9.9';DocsContract=1;DocsLayout='current';DocsCount=$currentDocs.Count;Docs=@($currentDocs.Entries)};$currentOuterPath=Join-Path $currentRoot 'Void-9.9.9-win32-x64-distribution-bundle.zip';New-CurrentOuterFixtureZip $currentOuterPath $currentPortablePath $production;$currentOuter=Assert-OuterArchive $currentOuterPath;$currentOuterHistorical=Assert-OuterArchive $currentOuterPath -HistoricalArchive;$currentOuterPair=Assert-OuterArchive $currentOuterPath $currentPortableMeta;if($currentOuter.DocsLayout -cne 'current' -or $currentOuterHistorical.DocsLayout -cne 'current' -or $currentOuterPair.DocsLayout -cne 'current' -or $currentOuter.Entries -ne 11 -or $currentOuter.OuterDocsCount -ne 9 -or $currentOuter.ChecksumRecordCount -ne 10 -or $currentOuter.SharedDocsCount -ne 0 -or $currentOuterHistorical.SharedDocsCount -ne 0 -or $currentOuterPair.SharedDocsCount -ne 8){throw 'Current outer checks did not report physical11/outer-docs9/checksum10/null-shared0/paired-shared8/layout current.'};Add-Pass 'current outer null self-check and paired shared-byte validation exact counts'
    $priorCurrentOuterPath=Join-Path $currentRoot 'Void-9.9.9-prior-current-win32-x64-distribution-bundle.zip';New-CurrentOuterFixtureZip $priorCurrentOuterPath $currentPortablePath $production -ReadmeOverride "# prior current snapshot`n4 accepted`n";$priorCurrentHistorical=Assert-OuterArchive $priorCurrentOuterPath $currentPortableMeta -HistoricalArchive;if($priorCurrentHistorical.DocsLayout -cne 'current' -or $priorCurrentHistorical.Entries -ne 11 -or $priorCurrentHistorical.OuterDocsCount -ne 9 -or $priorCurrentHistorical.ChecksumRecordCount -ne 10 -or $priorCurrentHistorical.SharedDocsCount -ne 8 -or $priorCurrentHistorical.InnerSha256 -cne $currentPortableMeta.Sha256){throw 'Historical prior-current outer did not preserve current-layout structure, checksums, shared bytes, and inner identity.'};Add-Pass 'historical prior-current semantic drift preserves structural pair validation';$strictPriorCurrentError=$null;try{Assert-OuterArchive $priorCurrentOuterPath $currentPortableMeta|Out-Null}catch{$strictPriorCurrentError=$_.Exception.Message};if($strictPriorCurrentError -cne 'Outer current text retains a stale universal Agent claim: 4 accepted'){throw "Strict prior-current semantic failure mismatch: $strictPriorCurrentError"};Add-Pass 'strict current rejects prior-current stale semantics'

    $partialZip=Join-Path $positive.Root 'partial.zip';New-DocsFixtureZip $partialZip $positiveManifest partial;Assert-Throws 'partial docs rejected' {Test-DocsFixtureZip $partialZip $positiveManifest|Out-Null}
    $extraZip=Join-Path $positive.Root 'extra.zip';New-DocsFixtureZip $extraZip $positiveManifest extra;Assert-Throws 'unlisted docs rejected' {Test-DocsFixtureZip $extraZip $positiveManifest|Out-Null}
    $mismatchZip=Join-Path $positive.Root 'mismatch.zip';New-DocsFixtureZip $mismatchZip $positiveManifest mismatch;Assert-Throws 'current prepared candidate rejects old release-notes' {Test-DocsFixtureZip $mismatchZip $positiveManifest 1 current|Out-Null};$historicalMismatch=Test-DocsFixtureZip $mismatchZip $positiveManifest 1 current -HistoricalArchive;if($historicalMismatch.Contract -ne 1 -or $historicalMismatch.Layout -cne 'current' -or $historicalMismatch.Count -ne 3){throw 'Historical current-layout release-notes fixture did not return contract metadata.'};$historicalNotes=@($historicalMismatch.Entries|Where-Object{$_.Path -ceq 'docs/release-notes.md'})[0];if($historicalNotes.Length -le 0 -or [string]::IsNullOrWhiteSpace($historicalNotes.Sha256)){throw 'Historical release-notes fixture did not return actual metadata.'};Add-Pass 'historical current layout retains actual metadata while current is byte strict'
    foreach($mode in @('partial','extra','empty','bom','path-mismatch')){$badZip=Join-Path $positive.Root ("historical-$mode.zip");New-DocsFixtureZip $badZip $positiveManifest $mode;Assert-Throws "historical $mode rejected" {Test-DocsFixtureZip $badZip $positiveManifest -HistoricalArchive|Out-Null}}

    $oldRoot=Join-Path $tempRoot 'old-layout';New-Item -ItemType Directory -Path $oldRoot|Out-Null;$oldPortablePath=Join-Path $oldRoot 'Void-9.9.9-win32-x64-portable.zip';New-HistoricalDocsFixtureZip $oldPortablePath $historicalSnapshot exact;$oldDocs=Test-DocsFixtureZip $oldPortablePath $production 1 8ad348e -HistoricalArchive;if($oldDocs.Layout -cne '8ad348e' -or $oldDocs.Count -ne 7){throw 'Exact old fixture did not resolve to 8ad348e/docs7.'};Add-Pass 'exact old portable layout passes historical mode';Assert-Throws 'exact old portable layout fails current mode' {Test-DocsFixtureZip $oldPortablePath $production 1|Out-Null};foreach($mode in @('partial','extra','path','case','bom','utf8','empty')){$bad=Join-Path $oldRoot "old-$mode.zip";New-HistoricalDocsFixtureZip $bad $historicalSnapshot $mode;Assert-Throws "old portable $mode rejected" {Test-DocsFixtureZip $bad $production 1 8ad348e -HistoricalArchive|Out-Null}}

    $oldPortableMeta=[pscustomobject]@{Path=$oldPortablePath;Size=(Get-Item $oldPortablePath).Length;Sha256=(Get-FileHash $oldPortablePath -Algorithm SHA256).Hash.ToLowerInvariant();Version='9.9.9';DocsContract=1;DocsLayout='8ad348e';DocsCount=$oldDocs.Count;Docs=@($oldDocs.Entries)};$oldOuterPath=Join-Path $oldRoot 'Void-9.9.9-win32-x64-distribution-bundle.zip';New-HistoricalOuterFixtureZip $oldOuterPath $oldPortablePath $oldPortableMeta $historicalSnapshot exact;$oldOuter=Assert-OuterArchive $oldOuterPath $oldPortableMeta -HistoricalArchive;$oldOuterSelf=Assert-OuterArchive $oldOuterPath -HistoricalArchive;if($oldOuter.DocsLayout -cne '8ad348e' -or $oldOuterSelf.DocsLayout -cne '8ad348e' -or $oldOuter.Entries -ne 7 -or $oldOuter.OuterDocsCount -ne 5 -or $oldOuter.ChecksumRecordCount -ne 6 -or $oldOuter.SharedDocsCount -ne 4){throw 'Old outer fixture did not report physical7/outer-docs5/checksum6/shared4/layout8ad348e.'};Add-Pass 'old outer historical pair and null-expected self-check exact counts';Assert-Throws 'old outer without current Agent anchors fails current mode' {Assert-OuterArchive $oldOuterPath $oldPortableMeta|Out-Null};foreach($mode in @('partial','extra','path','case','bom','utf8','shared-mismatch')){$bad=Join-Path $oldRoot "old-outer-$mode.zip";New-HistoricalOuterFixtureZip $bad $oldPortablePath $oldPortableMeta $historicalSnapshot $mode;Assert-Throws "old outer $mode rejected" {Assert-OuterArchive $bad $oldPortableMeta -HistoricalArchive|Out-Null}}

    $outerMaterialized=Join-Path $positive.Root 'outer-materialized';New-Item -ItemType Directory -Path $outerMaterialized|Out-Null;$tokens=@{'{{PORTABLE_SIZE}}'='1 byte';'{{PORTABLE_SHA256}}'=('a'*64);'{{PORTABLE_ENTRIES}}'='4';'{{SOURCE_HEAD}}'=('b'*40);'{{BUILD_DATE_KST}}'='2026-08-06 KST'};$outerPlan=@(Write-ReleaseContentOuterFiles $positiveManifest $outerMaterialized $tokens);$portablePlan=@(Get-ReleaseContentPlan $positiveManifest Portable -ProductVersion '9.9.9');$outerShared=[IO.File]::ReadAllBytes((Join-Path $outerMaterialized 'guides\guide.md'));$portableShared=[byte[]](@($portablePlan|Where-Object{$_.Path -ceq 'docs/guides/guide.md'})[0].Bytes);if(-not(Test-ReleaseContentBytesEqual $outerShared $portableShared)){throw 'Shared outer/portable fixture bytes differ.'};Add-Pass 'shared outer portable bytes'
    $sharedEntry=@($positiveManifest.Entries|Where-Object{$_.Source -ceq 'shared/guide.md'})[0];$historicalShared=[byte[]]$Utf8NoBom.GetBytes("# Historical guide`n");$historicalRecord=[pscustomobject]@{Path='docs/guides/guide.md';Length=$historicalShared.Length;Sha256=(Get-ReleaseContentBytesSha256 $historicalShared)};Assert-ReleaseContentSharedArchiveBytes -Entry $sharedEntry -OuterBytes $historicalShared -PortableRecord $historicalRecord -HistoricalArchive;Assert-Throws 'strict shared docs reject historical current-source mismatch' {Assert-ReleaseContentSharedArchiveBytes -Entry $sharedEntry -OuterBytes $historicalShared -PortableRecord $historicalRecord};$mismatchedHistoricalRecord=[pscustomobject]@{Path='docs/guides/guide.md';Length=($historicalShared.Length+1);Sha256=$historicalRecord.Sha256};Assert-Throws 'historical shared outer portable mismatch rejected' {Assert-ReleaseContentSharedArchiveBytes -Entry $sharedEntry -OuterBytes $historicalShared -PortableRecord $mismatchedHistoricalRecord -HistoricalArchive};Add-Pass 'historical shared outer portable metadata'

    $artifact=Join-Path $positive.Root 'artifact';New-Item -ItemType Directory -Path (Join-Path $artifact 'data') -Force|Out-Null;Write-FixtureText (Join-Path $artifact 'app.txt') "artifact`n";Write-FixtureText (Join-Path $artifact 'data\argv.json') "generated`n"
    $workspaceRoot=Split-Path -Parent (Split-Path -Parent (Split-Path -Parent $PSScriptRoot));$node=Join-Path $workspaceRoot '.toolchain\node-v20.18.2-win-x64\node.exe';if(-not(Test-Path -LiteralPath $node -PathType Leaf)){$node=(Get-Command node -ErrorAction Stop).Source};$packer=Join-Path $PSScriptRoot 'package-portable.js'

    $dotAlias=New-FixtureCase $tempRoot 'dot-alias';Write-FixtureText (Join-Path $dotAlias.ContentRoot 'portable\item.md') "item`n";Write-FixtureText (Join-Path $dotAlias.ContentRoot 'portable\item-other.md') "other`n";$dotAlias.Manifest.entries+=,[ordered]@{source='portable/item.md';portablePath='docs/item';materialization='copy'};$dotAlias.Manifest.entries+=,[ordered]@{source='portable/item-other.md';portablePath='docs/item.';materialization='copy'};Write-FixtureManifest $dotAlias $dotAlias.Manifest;Assert-ManifestRejectedByPowerShellAndJavaScript 'item versus item-dot alias' $dotAlias $node $packer $artifact
    $spaceAlias=New-FixtureCase $tempRoot 'space-alias';$spaceAlias.Manifest.entries[1].portablePath='docs/trailing /README.md';Write-FixtureManifest $spaceAlias $spaceAlias.Manifest;Assert-ManifestRejectedByPowerShellAndJavaScript 'trailing-space segment' $spaceAlias $node $packer $artifact
    $reservedAlias=New-FixtureCase $tempRoot 'reserved-alias';$reservedAlias.Manifest.entries[1].portablePath='docs/CON.md';Write-FixtureManifest $reservedAlias $reservedAlias.Manifest;Assert-ManifestRejectedByPowerShellAndJavaScript 'reserved-device segment' $reservedAlias $node $packer $artifact
    $exactRoute=New-FixtureCase $tempRoot 'exact-route';Write-FixtureText (Join-Path $exactRoute.ContentRoot 'shared\guide.md') "gpt-5.6-luna-2026-07-09`n";Assert-ManifestRejectedByPowerShellAndJavaScript 'exact internal route privacy' $exactRoute $node $packer $artifact
    $datedRoute=New-FixtureCase $tempRoot 'dated-route';Write-FixtureText (Join-Path $datedRoute.ContentRoot 'shared\guide.md') "gpt-9.9-internal-2030-01-02`n";Assert-ManifestRejectedByPowerShellAndJavaScript 'dated internal route privacy' $datedRoute $node $packer $artifact

    $packed=Join-Path $positive.Root 'packed-one.zip';$packedAgain=Join-Path $positive.Root 'packed-two.zip';Invoke-FixturePacker $node $packer $artifact $packed $positive.ManifestPath;Start-Sleep -Milliseconds 2200;Invoke-FixturePacker $node $packer $artifact $packedAgain $positive.ManifestPath
    $packedHash=(Get-FileHash -Algorithm SHA256 -LiteralPath $packed).Hash;$packedAgainHash=(Get-FileHash -Algorithm SHA256 -LiteralPath $packedAgain).Hash;$packedBytes=[IO.File]::ReadAllBytes($packed);$packedAgainBytes=[IO.File]::ReadAllBytes($packedAgain);if($packedHash -cne $packedAgainHash -or -not(Test-ReleaseContentBytesEqual $packedBytes $packedAgainBytes)){throw "Two identical packer runs were not byte-identical: $packedHash / $packedAgainHash"};Add-Pass 'two-run deterministic supplemental ZIP bytes'
    if(Test-Path -LiteralPath (Join-Path $artifact 'docs')){throw 'Fixture packer mutated ArtifactRoot with docs.'}
    $packedZip=[IO.Compression.ZipFile]::OpenRead($packed);try{$names=@($packedZip.Entries|ForEach-Object{$_.FullName});if($names -ccontains 'data/argv.json'){throw 'Fixture packer included generated user data.'};$sorted=@($names);[Array]::Sort($sorted,[StringComparer]::Ordinal);if(($names -join "`n") -cne ($sorted -join "`n")){throw 'Fixture packer entry order is not deterministic ordinal order.'};$by=@{};foreach($entry in $packedZip.Entries){$by[$entry.FullName]=$entry};$packedDocs=Assert-ReleaseContentArchiveDocsContract $by $positiveManifest '9.9.9' -RequiredContract 1;if($packedDocs.Count -ne 3){throw 'Fixture packer docs count mismatch.'}}finally{$packedZip.Dispose()};Add-Pass 'direct ZIP supplemental package content'

    [pscustomobject]@{status='passed';tests=$Results.Count;checks=@($Results)}|ConvertTo-Json -Depth 4
} finally {
    if(Test-Path -LiteralPath $tempRoot){$item=Get-Item -LiteralPath $tempRoot -Force;if(($item.Attributes -band [IO.FileAttributes]::ReparsePoint) -ne 0){throw 'Refusing to remove a reparse-point fixture root.'};if(-not $item.FullName.StartsWith($tempParent,[StringComparison]::OrdinalIgnoreCase)){throw 'Refusing to remove a fixture outside the system temporary directory.'};[IO.Directory]::Delete($item.FullName,$true)}
}
